OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::PostProcessing::WaterSorptionResponse< dim > Class Template Reference
FuelCellShop::PostProcessing::WaterSorptionResponse< dim > Class Template Reference
Class used to calculate the amount of water sorbed inside the catalyst layer.
#include <response_water_sorption.h>
Public Member Functions
Constructor, declaration and initialization
WaterSorptionResponse (const FuelCell::SystemManagement &sm, const FuelCellShop::Equation::SorptionSourceTerms< dim > *sst)
~WaterSorptionResponse ()
void initialize (ParameterHandler &param)
Initialize class parameters.
Compute functional
const
FuelCellShop::Equation::SorptionSourceTerms
< dim > * sorption_source
Pointer to SorptionSourceTerms object.
double time_k
Rate of sorption/desorption.
FuelCellShop::Equation::VariableInfo lambda
VariableInfo structure corresponding to the "membrane_water_content".
FuelCellShop::Equation::VariableInfo x_w
VariableInfo structure corresponding to the "water_molar_fraction".
FuelCellShop::Equation::VariableInfo tRev
VariableInfo structure corresponding to the "temperature_of_REV".
void compute_responses (const typename DoFApplication< dim >::CellInfo &info, FuelCellShop::Layer::BaseLayer< dim > *const layer, std::map< FuelCellShop::PostProcessing::ResponsesNames, double > &respMap) const
This member function computes the water adsorbed/desorbed from the electrolyte in the catalyst layer.
void compute_responses (std::vector< FuelCellShop::SolutionVariable > solution_variables, const typename DoFApplication< dim >::CellInfo &info, FuelCellShop::Layer::BaseLayer< dim > *const layer, std::map< FuelCellShop::PostProcessing::ResponsesNames, double > &resp) const
Routine used in order to compute the response with a modified solution (not the one stored in info)
Additional Inherited Members
Protected Member Functions inherited from FuelCellShop::PostProcessing::BaseResponse< dim >
BaseResponse (const FuelCell::SystemManagement &sm)
Constructor.
virtual ~BaseResponse ()
Destructor.
virtual void declare_parameters (ParameterHandler &param) const
Declare any necessary parameters to compute the functional.
Protected Attributes inherited from FuelCellShop::PostProcessing::BaseResponse< dim >
const FuelCell::SystemManagement * system_management
Pointer to system management.
Detailed Description
template<int dim>
class FuelCellShop::PostProcessing::WaterSorptionResponse< dim >
Class used to calculate the amount of water sorbed inside the catalyst layer.
This class returns the total water amount sorbed inside the layer, i.e.
If the response value is negative, it implies that water is desorbed from the catalyst layer. Applications can divide the obtained total quantity by surface area, volume etc. of the layer, in order to determine surface density, volumetric density etc.
Remarks
This class will not work if anything other than the CL layer object is passed as argument.
FuelCellShop::Equation::SorptionSourceTerms object reference is required in the constructor, besides the FuelCell::SystemManagement object reference.
and , should be solved for in the application.
Usage
In order to use this classes, first add them to your application as an object.
* #include "postprocessing/response_water_sorption.h"
*
* (...)
*
*  FuelCellShop::PostProcessing::WaterSorptionResponse<dim> waterSorption;
*
In the class constructor, construct the class passing SystemManagement and SorptionSourceTerms object. These objects are used in order to find the solution variables as appropriate, and flag parameters.
* //---------------------------------------------------------------------------
* template <int dim>
* NAME::AppPemfcNIThermal<dim>::AppPemfcNIThermal(boost::shared_ptr<FuelCell::ApplicationCore::ApplicationData> data)
* :
* OptimizationBlockMatrixApplication<dim>(data),
* system_management(this->block_info, this->cell_couplings, this->flux_couplings),
* sorption_source_terms(system_management)
* waterSorption(system_management, &sorption_source_terms)
* {}
*
Note that unlike some response classes, this class is not required to declare parameters, as it is already deriving flag parameters from SorptionSourceTerms object.
Next, the object has to be initialized once SystemManagement and SorptionSourceTerms objects have already been initialized:
* // Initialize parameters in system management:
* system_management.initialize(param);
* sorption_source_terms.initialize(param);
* //Initialize post-processing routines:
* waterSorption.initialize(param);
*
Finally, the object is ready for use in cell_responses in your application:
* // Compute Total amount of water sorbed in the CCL
*    std::map<FuelCellShop::PostProcessing::ResponsesNames, double> respMap;
* if (CCL->belongs_to_material(material_id)) //the material is the cathode catalyst layer
*        waterSorption.compute_responses(cellInfo, CCL.get(), respMap);
*
Author
M. Secanell, 2014
Madhur Bhaiya, 2014
Constructor & Destructor Documentation
template<int dim> FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::WaterSorptionResponse (const FuelCell::SystemManagement & sm, const FuelCellShop::Equation::SorptionSourceTerms< dim > * sst) inline
template<int dim> FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::~WaterSorptionResponse () inline
Member Function Documentation
template<int dim> void FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::compute_responses (const typename DoFApplication< dim >::CellInfo & info, FuelCellShop::Layer::BaseLayer< dim > *const layer, std::map< FuelCellShop::PostProcessing::ResponsesNames, double > & respMap) const inline virtual
This member function computes the water adsorbed/desorbed from the electrolyte in the catalyst layer.
In order to compute the water sorption, the following functional is evaluated
In order to access the sorbed water at the electrode use:
* ORR_responses[FuelCellShop::PostProcessing::ResponsesNames::sorbed_water]
*
Implements FuelCellShop::PostProcessing::BaseResponse< dim >.
References FuelCell::ApplicationCore::IntegrationInfo< dim, FEVALUESBASE >::fe(), FuelCellShop::Layer::BaseLayer< dim >::get_base_type(), FuelCellShop::Material::PolymerElectrolyteBase::get_density(), FuelCellShop::Layer::CatalystLayer< dim >::get_electrolyte(), FuelCellShop::Material::PolymerElectrolyteBase::get_EW(), FuelCell::ApplicationCore::IntegrationInfo< dim, FEVALUESBASE >::global_data, FuelCellShop::Material::PolymerElectrolyteBase::set_temperature(), FuelCellShop::Material::PolymerElectrolyteBase::set_water_molar_fraction(), FuelCellShop::PostProcessing::sorbed_water, FuelCellShop::Material::PolymerElectrolyteBase::sorption_isotherm(), temperature_of_REV, FuelCell::ApplicationCore::IntegrationInfo< dim, FEVALUESBASE >::values, and water_molar_fraction.
template<int dim> void FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::compute_responses (std::vector< FuelCellShop::SolutionVariable > solution_variables, const typename DoFApplication< dim >::CellInfo & info, FuelCellShop::Layer::BaseLayer< dim > *const layer, std::map< FuelCellShop::PostProcessing::ResponsesNames, double > & resp) const inline virtual
Routine used in order to compute the response with a modified solution (not the one stored in info)
Implements FuelCellShop::PostProcessing::BaseResponse< dim >.
template<int dim> void FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::initialize (ParameterHandler & param) inline virtual
Initialize class parameters.
Reimplemented from FuelCellShop::PostProcessing::BaseResponse< dim >.
Member Data Documentation
template<int dim> FuelCellShop::Equation::VariableInfo FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::lambda private
VariableInfo structure corresponding to the "membrane_water_content".
template<int dim> const FuelCellShop::Equation::SorptionSourceTerms<dim>* FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::sorption_source private
Pointer to SorptionSourceTerms object.
template<int dim> double FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::time_k private
Rate of sorption/desorption.
Specified by SorptionSourceTerms in parameter file section Sorption Source Terms >> Water soption time constant [1/s]
template<int dim> FuelCellShop::Equation::VariableInfo FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::tRev private
VariableInfo structure corresponding to the "temperature_of_REV".
template<int dim> FuelCellShop::Equation::VariableInfo FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::x_w private
VariableInfo structure corresponding to the "water_molar_fraction".
The documentation for this class was generated from the following file:
response_water_sorption.h