OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::MicroScale::HybridAgglomerate Class Reference
FuelCellShop::MicroScale::HybridAgglomerate Class Reference
Class that solves a Hybrid (water/ionomer filled) agglomerate problem in 1D.
#include <agglomerate_hybrid_1D.h>
Public Member Functions
virtual std::string get_name ()
Return name of class instance, i.e.
virtual double aux_volume_fraction ()
Functions directly inherited from parent.
virtual void print_properties ()
Print out key agglomerate information (name, radius, film thickness, porosity).
Public Member Functions inherited from FuelCellShop::MicroScale::WaterAgglomerate
virtual SolutionMap compute_current ()
Main function of the class used to compute the current over the whole agglomerate at the local operating conditions.
Public Member Functions inherited from FuelCellShop::MicroScale::AgglomerateBase
virtual ~AgglomerateBase ()
virtual std::vector< double > compute_derivative_current ()
Function to compute the derivative of the current density at the local operating conditions.
virtual bool has_derivatives ()
Returns true if the class instance can calculate current density derivatives.
virtual void set_solution (const std::map< VariableNames, SolutionVariable > &, const VariableNames &, const int &)
Function for setting the solution map(reactant concentration, phi_s, phi_m, etc.).
Public Member Functions inherited from FuelCellShop::MicroScale::MicroScaleBase
virtual ~MicroScaleBase ()
Destructor.
Public Member Functions inherited from FuelCell::ApplicationCore::DAEWrapper
DAEWrapper ()
Constructor.
~DAEWrapper ()
Destructor.
double integrate (double lb, double ub, std::vector< double > &W, std::vector< double > &F)
Member function that integrates a solution between a lower and upper bound.
void get_quadrature_points (double lb, double ub, std::vector< double > &X, std::vector< double > &W, FuelCell::ApplicationCore::DAESolver *prob)
Function that obtains the gaussian quadrature points and weights.
void verbosity (int i)
Set the verbosity variable (controls output to screen)
void DAE_Error (int flag)
Indicates error in the solve function.
void clear_memory ()
Static Public Attributes
static const std::string concrete_name
Static Public Attributes inherited from FuelCellShop::MicroScale::WaterAgglomerate
static const std::string concrete_name
Protected Member Functions
void set_structure ()
Functions directly inherited from parent.
HybridAgglomerate (int verbose=1)
Constructors.
HybridAgglomerate (std::string concrete_name)
virtual void declare_parameters (ParameterHandler &param) const
virtual void initialize (ParameterHandler &param)
double compute_thickness_agg ()
Member function to compute the thickness of the agglomerate thin film based on the radius and structure.
virtual double compute_epsilon_agg ()
Compute the volume fraction of nafion inside the agglomerate given the catalyst layer ionomer volume fraction , ; size of the agglomerate, ; and, porosity inside the agglomerate, , the necessary ionomer thin film thickness is computed such that the correct volume fractions are obtained.
void fsub (double &, double[], double[], double[])
Define the DAE function.
void dfsub (double &, double[], double[], double[])
The Jacobian of fsub.
Protected Member Functions inherited from FuelCellShop::MicroScale::WaterAgglomerate
int cont_tolerance (double start_tol, double end_tol)
Function which implements a continuation based on the tolerance.
int cont_cd ()
Function which implements a continuation based on lambda - modifying the source terms to scale back the equations.
void setup_DAE_solver ()
Setup the variables in the problem required by the DAE Solver.
virtual double get_film_thickness ()
virtual double get_radius ()
void set_structure ()
Set the composition and structure of the agglomerate.
WaterAgglomerate (int verbose=1)
Constructors.
WaterAgglomerate (std::string concrete_name)
double compute_thickness_agg ()
Member function to compute the thickness of the agglomerate thin film based on the radius and structure.
void fsub (double &, double[], double[], double[])
Define the DAE function.
void dfsub (double &, double[], double[], double[])
The Jacobian of fsub.
void gsub (int &, double[], double &)
Define the boundary conditions.
void dgsub (int &, double[], double[])
The derivatives of the boundary conditions.
void guess (double &, double[], double[], double[])
The initial guess.
Protected Member Functions inherited from FuelCellShop::MicroScale::NumericalAgglomerateBase
void setAV (double newAV)
NumericalAgglomerateBase ()
Constructor.
~NumericalAgglomerateBase ()
Destructor.
void update_initial_solution ()
void save_initial_solution ()
double getAV (double location)
bool use_initial_data (double z[], const double &x)
virtual void make_thread_safe (ParameterHandler &param, unsigned int thread_index)
Protected Member Functions inherited from FuelCellShop::MicroScale::AgglomerateBase
void _initialize_film_porosity ()
AgglomerateBase ()
virtual double compute_epsilon_N (const double delta_agg, const double thickness_agg) const
Function used to compute the amount of electrolyte in the catalyst layer.
virtual double compute_depsilonN_dthickness (const double thickness_agg) const
Function to compute
This function should only be used to calculate the thin film thickness using Newton's method.
virtual double compute_depsilonN_depsilon_agg () const
Inline function to compute
This function should only be used to calculate the thin film thickness using Newton's method.
virtual double compute_n () const
Member function to compute the number of agglomerates.
virtual double compute_dn_depsilon_agg () const
Compute the derivative of n with respect to the porosity of the agglomerate.
Protected Member Functions inherited from FuelCellShop::MicroScale::MicroScaleBase
void set_layer (FuelCellShop::Layer::MultiScaleCL< deal_II_dimension > *_layer)
MicroScaleBase ()
Static Protected Member Functions
static void fsub_wrapper (double &, double[], double[], double[])
static void dfsub_wrapper (double &, double[], double[], double[])
Static Protected Member Functions inherited from FuelCellShop::MicroScale::WaterAgglomerate
static void fsub_wrapper (double &, double[], double[], double[])
static void dfsub_wrapper (double &, double[], double[], double[])
static void gsub_wrapper (int &, double[], double &)
static void dgsub_wrapper (int &, double[], double[])
static void guess_wrapper (double &, double[], double[], double[])
Static Protected Member Functions inherited from FuelCellShop::MicroScale::MicroScaleBase
static _mapFactory * get_mapFactory ()
This member function is used to create an object of type MicroScaleBase.
Private Attributes
double hybrid_interface
Object inheritted from water filled agglomerate.
double hybrid_core_volume_fraction
Instance Delivery
static HybridAgglomerate const * PROTOTYPE
virtual boost::shared_ptr
< FuelCellShop::MicroScale::MicroScaleBase > create_replica ()
This member function is used to create an object of type MicroScaleBase.
Additional Inherited Members
Static Public Member Functions inherited from FuelCellShop::MicroScale::MicroScaleBase
static void declare_MicroScale_parameters (ParameterHandler &param)
Function used to declare all the data necessary in the parameter files for all MicroScale children.
static boost::shared_ptr
< FuelCellShop::MicroScale::MicroScaleBase > create_MicroStructure (ParameterHandler &param, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension > *layer)
Function used to select the appropriate MicroScale type as specified in the ParameterHandler under line.
Protected Types inherited from FuelCellShop::MicroScale::AgglomerateBase
typedef
FuelCellShop::Layer::MultiScaleCL
< deal_II_dimension >
::Properties CLPropNames
typedef std::map< CLPropNames,
double > CL_Properties
Protected Types inherited from FuelCellShop::MicroScale::MicroScaleBase
typedef std::map< std::string,
MicroScaleBase * > _mapFactory
This object is used to store all objects of type MicroScaleBase.
Protected Attributes inherited from FuelCellShop::MicroScale::WaterAgglomerate
FuelCellShop::Material::LiquidWater water
Object to store information on water, necessary for water filled agglomerate.
double D_H_NAF
Proton Diffusivity in Nafion and water.
double D_H_Water
double D_O2_N
Oxygen Diffusivity in Nafion and water.
double DO2_Water
double HO2N
Henry's Constant for oxygen in nafion.
double rel_permittivity_water
double rel_permittivity_Naf
double core_charge_factor
std::vector< std::string > derivative_flags
double H_tol
absolute tolerance in proton concentration
double lambda
double lambda2
Protected Attributes inherited from FuelCellShop::MicroScale::NumericalAgglomerateBase
std::vector< std::vector
< double > > final_results
std::vector< std::vector
< double > > initial_solution
std::vector< std::string > column_names
double R_tol
Protected Attributes inherited from FuelCellShop::MicroScale::AgglomerateBase
boost::shared_ptr
< FuelCellShop::Material::CatalystBase > catalyst
Boost shared pointer to catalyst object.
boost::shared_ptr
< FuelCellShop::Material::PolymerElectrolyteBase > electrolyte
Boost shared pointer to electrolyte object.
boost::shared_ptr
< FuelCellShop::Kinetics::BaseKinetics > kinetics
Boost shared pointer to kinetics object.
std::map< VariableNames,
SolutionVariable > solutions
Member data for storing solutions.
std::vector< VariableNames > sol_names
VariableNames reactant
VariableNames tempReactantName
int sol_index
double permittivity_0
Constants.
double pi
double F
double R
double P
double AV
double r_agg
double delta_agg
double epsilon_agg
double c_R
bool has_derivatives_
double c_H
double phi_M
double phi_S
double interface
double D_R_N
double H_R_N
Henry's Constant for primary reactant in nafion, [Pa cm^3/mol].
std::string fixed_agg_variable
double n_agg
Protected Attributes inherited from FuelCellShop::MicroScale::MicroScaleBase
FuelCellShop::Layer::MultiScaleCL
< deal_II_dimension > * layer
Protected Attributes inherited from FuelCell::ApplicationCore::DAEWrapper
int n_mesh
Number of mesh points.
double * mesh
Array of mesh points.
int n_colloc
Number of collocation points.
int n_output
Output integer variable.
int n_comp
number of PDEs
int n_y
number of Algebraic constraints
int * mm
array of integers storing the order of each PDE
int m_star
Integer representing the total number of variables given by .
double boundary_0
Left boundary point.
double boundary_1
Right boundary point.
double * zeta
Array of boundary points.
FuelCell::ApplicationCore::DAESolver * prob
DAE problem solver object.
double * fixpnt
Array of fixed points on the mesh.
int * ltol
double * tol
double cm_to_m
Convert from centimetres to metres.
double cm2_to_m2
Convert from centimetres squared to metres squared.
double cm3_to_m3
Convert from centimetres cubed to metres cubed.
Static Protected Attributes inherited from FuelCellShop::MicroScale::WaterAgglomerate
static WaterAgglomerate const * PROTOTYPE
Detailed Description
Class that solves a Hybrid (water/ionomer filled) agglomerate problem in 1D.
This class uses the DAE solver interface to solve the problem using COLDAE (included in the contrib folder) to solve a boundary value problem.
Constructor & Destructor Documentation
FuelCellShop::MicroScale::HybridAgglomerate::HybridAgglomerate (int verbose = 1) protected
Constructors.
FuelCellShop::MicroScale::HybridAgglomerate::HybridAgglomerate (std::string concrete_name) protected
Member Function Documentation
virtual double FuelCellShop::MicroScale::HybridAgglomerate::aux_volume_fraction () inline virtual
Functions directly inherited from parent.
-double compute_current (double &E_r) -virtual std::string get_name() MicroScale object may have extra contribution to volume of layer, e.g. water.
The assumption of a hybrid core means that this contribution is different than in the pure water filled case, thus it is reimplemented here.
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
References FuelCellShop::MicroScale::WaterAgglomerate::aux_volume_fraction(), and hybrid_core_volume_fraction.
virtual double FuelCellShop::MicroScale::HybridAgglomerate::compute_epsilon_agg () protected virtual
Compute the volume fraction of nafion inside the agglomerate given the catalyst layer ionomer volume fraction , ; size of the agglomerate, ; and, porosity inside the agglomerate, , the necessary ionomer thin film thickness is computed such that the correct volume fractions are obtained.
A Newton loop is used in order to obtain the correct value for the agglomerate porosity, .
Note
compute_thickness_agg and compute_epsilon_agg are mutually exclusive and the selection between using one method or the other depends on the inpu parameter:
*      set Constant agglomerate parameter [Thickness | Porosity] = Thickness
*      set Agglomerate porosity = 0.25               #specify if Porosity is selected in variable above
*      set Thickness of the agglomerate film [nm] = 80               #specify if Thickness is selected in property above
*
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
double FuelCellShop::MicroScale::HybridAgglomerate::compute_thickness_agg () protected virtual
Member function to compute the thickness of the agglomerate thin film based on the radius and structure.
For a given ionomer volume fraction, ; size of the agglomerate, ; and, porosity inside the agglomerate, , the necessary ionomer thin film thickness is computed such that the correct volume fractions are obtained.
A Newton loop is used in order to obtain the correct value for the thickness of the agglomerate film,
Note
compute_thickness_agg and compute_epsilon_agg are mutually exclusive and the selection between using one method or the other depends on the inpu parameter:
*      set Constant agglomerate parameter [Thickness | Porosity] = Thickness
*      set Agglomerate porosity = 0.25               #specify if Porosity is selected in variable above
*      set Thickness of the agglomerate film [nm] = 80               #specify if Thickness is selected in property above
*
Reimplemented from FuelCellShop::MicroScale::AgglomerateBase.
virtual boost::shared_ptr<FuelCellShop::MicroScale::MicroScaleBase> FuelCellShop::MicroScale::HybridAgglomerate::create_replica () inline protected virtual
This member function is used to create an object of type MicroScaleBase.
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
virtual void FuelCellShop::MicroScale::HybridAgglomerate::declare_parameters (ParameterHandler & param) const inline protected virtual
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
References concrete_name, FuelCellShop::Material::LiquidWater::declare_parameters(), FuelCellShop::MicroScale::NumericalAgglomerateBase::declare_parameters(), and FuelCellShop::MicroScale::WaterAgglomerate::water.
void FuelCellShop::MicroScale::HybridAgglomerate::dfsub (double & , double [], double [], double []) protected virtual
The Jacobian of fsub.
Until we decide on how to get AD support in FCST, we must enter the Jacobian in manually. Note that a one-dimensional array must be passed back to COLDAE. However, it is easier to define a two-dimensional array as the matrix (see COLDAE.f). After, use c_to_for_matrix to convert it to the correct one-dimensional array.
Implements FuelCell::ApplicationCore::DAEWrapper.
static void FuelCellShop::MicroScale::HybridAgglomerate::dfsub_wrapper (double & , double [], double [], double []) static protected
void FuelCellShop::MicroScale::HybridAgglomerate::fsub (double & , double [], double [], double []) protected virtual
Define the DAE function.
In this case,it is simply a system of ODES. COLDAE allows for the system to be defined as a system of 2 mixed-order ODEs. See COLDAE.f for additional information about how to define fsub. In particular, see COLDAE.f for the meaning of z and y. Note that because a BVP is solved, y is not used.
Implements FuelCell::ApplicationCore::DAEWrapper.
static void FuelCellShop::MicroScale::HybridAgglomerate::fsub_wrapper (double & , double [], double [], double []) static protected
virtual std::string FuelCellShop::MicroScale::HybridAgglomerate::get_name () inline virtual
Return name of class instance, i.e.
concrete name.
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
References concrete_name.
virtual void FuelCellShop::MicroScale::HybridAgglomerate::initialize (ParameterHandler & param) inline protected virtual
Reimplemented from FuelCellShop::MicroScale::WaterAgglomerate.
References concrete_name, hybrid_core_volume_fraction, FuelCellShop::Material::LiquidWater::initialize(), FuelCellShop::MicroScale::NumericalAgglomerateBase::initialize(), and FuelCellShop::MicroScale::WaterAgglomerate::water.
virtual void FuelCellShop::MicroScale::HybridAgglomerate::print_properties () virtual
Print out key agglomerate information (name, radius, film thickness, porosity).
Reimplemented from FuelCellShop::MicroScale::AgglomerateBase.
void FuelCellShop::MicroScale::HybridAgglomerate::set_structure () protected virtual
Functions directly inherited from parent.
-int cont_tolerance (double start_tol, double end_tol) -int cont_cd () -void setup_DAE_solver () -virtual double get_film_thickness() -virtual double get_radius() -void gsub (int &, double [], double &) -static void gsub_wrapper (int &, double [], double &) -void dgsub (int &, double [], double []) -static void dgsub_wrapper (int &, double [], double []) -void guess (double &, double [], double [], double []) -static void guess_wrapper (double &, double [], double [], double [])Set the composition and structure of the agglomerate
Structure is different to the pure water filled case, hence it is reimplemented here.
Implements FuelCellShop::MicroScale::MicroScaleBase.
Member Data Documentation
const std::string FuelCellShop::MicroScale::HybridAgglomerate::concrete_name static
Referenced by declare_parameters(), get_name(), and initialize().
double FuelCellShop::MicroScale::HybridAgglomerate::hybrid_core_volume_fraction private
Referenced by aux_volume_fraction(), and initialize().
double FuelCellShop::MicroScale::HybridAgglomerate::hybrid_interface private
Object inheritted from water filled agglomerate.
-FuelCellShop::Material::LiquidWater water
Transport Parameters Proton Diffusivity in Nafion and water -double D_H_NAF -double D_H_Water
Oxygen Diffusivity in Nafion and water
double D_O2_N -double DO2_Water
Henry's Constant for oxygen in nafion -double HO2N -double rel_permittivity_water -double rel_permittivity_Naf -std::vector<std::string> derivative_flags
absolute tolerance in proton concentration double H_tol
HybridAgglomerate const* FuelCellShop::MicroScale::HybridAgglomerate::PROTOTYPE static protected
The documentation for this class was generated from the following file:
agglomerate_hybrid_1D.h