OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Layer::CatalystLayer< dim > Class Template Reference
FuelCellShop::Layer::CatalystLayer< dim > Class Template Reference
Virtual class used to provide the interface for all CatalystLayer children.
#include <catalyst_layer.h>
Public Member Functions
virtual void set_cell_id (const unsigned int &id)
Function for setting current cell_id from applications.
std::string get_kinetics_type ()
Method for getting string describing kinetics type (corresponding to kinetics class concrete names)
virtual SolutionMap get_coverages ()
Method for getting coverages from kinetics objects (overloaded by MultiScaleCL)
Initalization
virtual void set_constant_solution (const double &value, const VariableNames &name)
Set those solution variables which are constant in the particular application.
virtual void set_solution (const std::vector< SolutionVariable > &)
This method is used to set the solution variable values in the kinetics object, at all quadrature points in the cell.
virtual void set_derivative_flags (const std::vector< VariableNames > &flags)
Method used to set the variables for which you would like to compute the derivatives in the catalyst layer.
void set_reaction_kinetics (const ReactionNames rxn_name)
Member function used to specify the reaction for which the kinetic parameters are needed, for example for a Platinum catalyst, we can specify that we need the kinetic parameters for either the oxygen reduction reaction (ORR) or the hydrogen oxidation reaction (HOR)
Accessors and info
const std::type_info & get_base_type () const
This member function returns a type_info object with the name of the base layer type the inherited class belongs to, i.e.
virtual void get_volume_fractions (std::map< std::string, double > &)
Compute the volume fractions of each phase.
virtual void get_loadings (std::map< std::string, double > &)
Return loadings.
Effective property calculators
virtual void effective_gas_diffusivity (const double &, const double &, double &) const
Compute the effective property in the pores of the CL.
virtual void effective_gas_diffusivity (std::vector< Tensor< 2, dim > > &) const
Return the effective diffusivity [m^2/s] for nonisothermal with/without two-phase case in the CL.
virtual void derivative_effective_gas_diffusivity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const
Return the derivative of effective diffusivity w.r.t solution variables/design parameters for nonisothermal with/without two-phase case in the CL.
virtual void effective_gas_diffusivity (Table< 2, Tensor< 2, dim > > &) const
Compute the effective property in the pores of the CL.
virtual void effective_electron_conductivity (double &) const
Compute the effective electron conductivity in the CL.
virtual void effective_electron_conductivity (Tensor< 2, dim > &) const
Compute the effective electron conductivity in the CL.
virtual void derivative_effective_electron_conductivity (std::vector< double > &) const
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
virtual void derivative_effective_electron_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
virtual void effective_proton_conductivity (double &) const
Compute the effective proton conductivity in the CL.
virtual void effective_proton_conductivity (std::vector< double > &) const
Compute the effective proton conductivity, at all quadrature points in the cell, mainly as a function of Temperature.
virtual void derivative_effective_proton_conductivity (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the effective proton conductivity in the CL with respect to either the solution or design parameters.
virtual void effective_thermal_conductivity (double &) const
Compute the effective thermal conductivity in the CL.
virtual void effective_thermal_conductivity (Tensor< 2, dim > &) const
Compute the effective thermal conductivity in the CL.
virtual void effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the effective thermal conductivity as a Tensor at all quadrature points.
virtual void derivative_effective_thermal_conductivity (std::vector< double > &) const
Compute the derivative of the effective thermal conductivity in the CL with respect to either the solution or design parameters.
virtual void derivative_effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective thermal conductivity in the CL with respect to either the solution or design parameters.
virtual void effective_water_diffusivity (double &) const
Compute the effective water diffusivity (lambda diffusivity) in the CL.
virtual void effective_water_diffusivity (std::vector< double > &) const
Compute the effective water diffusivity (lambda diffusivity) at all quadrature points in the CL.
virtual void derivative_effective_water_diffusivity (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the effective water diffusivity (lambda diffusivity) in the CL with respect to either the solution or design parameters.
virtual void effective_thermoosmotic_diffusivity (std::vector< double > &) const
Compute the effective thermo-osmotic diffusivity of lambda (sorbed water), at all quadrature points in the CL.
virtual void derivative_effective_thermoosmotic_diffusivity (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the effective thermo-osmotic diffusivity of lambda (sorbed water) in the CL with respect to either the solution or design parameters.
virtual void gas_permeablity (double &) const
Compute the CL gas permeability.
virtual void gas_permeablity (Tensor< 2, dim > &) const
Compute the CL gas permeability.
virtual void derivative_gas_permeablity (std::vector< double > &) const
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
virtual void derivative_gas_permeablity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
virtual void liquid_permeablity (std::vector< Tensor< 2, dim > > &) const
Compute the anisotropic CL liquid permeability , at all quadrature points in the cell.
virtual void derivative_liquid_permeablity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const
Compute the derivative of the anisotropic liquid permeability in the CL with respect to either the solution or design parameters, at all quadrature points in the cell.
virtual void pcapillary (std::vector< double > &) const
Compute , at all quadrature points in the cell.
virtual void dpcapillary_dsat (std::vector< double > &) const
Compute , at all quadrature points in the CL.
virtual void derivative_dpcapillary_dsat (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of in the CL, with respect to either the solution or design parameters, at all quadrature points in the cell.
virtual void interfacial_surface_area (std::vector< double > &) const
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the CL.
virtual void derivative_interfacial_surface_area (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the CL.
Reaction terms
virtual void current_density (std::vector< double > &)
This member function will use a FuelCellShop::BaseKinetics class in order to compute the current density production in the CL.
virtual void current_density (std::vector< double > &current, std::vector< double > &effectiveness)
This member function will use a FuelCellShop::BaseKinetics class in order to compute the current density production in the CL.
virtual void derivative_current_density (std::map< VariableNames, std::vector< double > > &)
This member function will use a FuelCellShop::BaseKinetics class in order to compute the derivative of the current density with respect to the variables setup using set_derivative_flags.
virtual double get_active_area_Pt () const
Get the active area of platinum per unit volume of CL.
virtual
FuelCellShop::Material::PolymerElectrolyteBase * get_electrolyte () const
Method to provide access to pointer of the electrolyte object of the catalyst layer.
virtual
FuelCellShop::Kinetics::BaseKinetics * get_kinetics () const
Method to provide access to pointer of the kinetic object of the catalyst layer.
Public Member Functions inherited from FuelCellShop::Layer::PorousLayer< dim >
void set_gases_and_compute (std::vector< FuelCellShop::Material::PureGas * > &gases_in, const double &pressure_in, const double &temperature_in)
Member function used to store all the gases that are in the pore space in the gas diffusion layer as well as their temperature [Kelvin] and total pressure [atm].
void compute_gas_diffusion (FuelCellShop::Material::PureGas *solute_gas, FuelCellShop::Material::PureGas *solvent_gas)
Member function used to compute bulk diffusion coefficients and derivatives w.r.t temperature for non-isothermal case and store inside the layer.
void set_gases (std::vector< FuelCellShop::Material::PureGas * > &gases_in, const double &pressure_in)
Member function used to store all the gases that are in the pore space in the porous layer.
void set_gas_mixture (FuelCellShop::Material::GasMixture &rgas_mixture)
Set gas_mixture.
void set_porosity_permeability_tortuosity_booleans (const bool &rporosity_is_constant, const bool &rpermeability_is_constant, const bool &rtortuosity_is_constant)
Set.
void set_temperature (const SolutionVariable &T_in)
Member function used to set the temperature [Kelvin] at every quadrature point inside the cell.
void set_saturation (const SolutionVariable &s_in)
Member function used to set the liquid water saturation at every quadrature point inside the cell.
FuelCellShop::Material::PureGas * get_gas_pointer (int index) const
Return the FuelCellShop::Material::PureGas pointer that is stored inside the class in the ith position.
std::vector
< FuelCellShop::Material::PureGas * > get_gases () const
Returns the vector of FuelCellShop::Material::PureGas pointers stored in the porous layer.
const
FuelCellShop::Material::GasMixture
*const get_gas_mixture () const
This function returns gas_mixture.
void get_gas_index (FuelCellShop::Material::PureGas *gas_type, int &index) const
Return the gas index in the GDL class.
void get_T_and_p (double &T, double &p) const
Return the constant temperature [Kelvin] and constant pressure [atm] inside the layer.
void get_p (double &p) const
Return the constant pressure [atm] inside the layer.
const bool & get_porosity_is_constant () const
This function returns porosity_is_constant.
const bool & get_permeability_is_constant () const
This function returns permeability_is_constant.
const bool & get_tortuosity_is_constant () const
This function returns tortuosity_is_constant.
double get_porosity () const
This function computes constant porosity in quadrature points of a mesh entity.
void get_porosity (std::vector< double > &dst) const
This function computes constant porosity in quadrature points of a mesh entity.
void get_porosity (std::vector< double > &dst, const std::vector< Point< dim > > &points) const
This function computes variable porosity in quadrature points of a mesh entity.
void get_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant permeability in quadrature points of a mesh entity.
void get_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable permeability in quadrature points of a mesh entity.
void get_SQRT_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes square root of constant permeability in quadrature points of a mesh entity.
void get_SQRT_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes square root of variable permeability in quadrature points of a mesh entity.
void get_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes inverse of constant permeability in quadrature points of a mesh entity.
void get_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes inverse of variable permeability in quadrature points of a mesh entity.
void get_SQRT_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes inverse of square root of constant permeability in quadrature points of a mesh entity.
void get_SQRT_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes inverse of square root of variable permeability in quadrature points of a mesh entity.
void get_Forchheimer_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant Forchheimer permeability in quadrature points of a mesh entity.
void get_Forchheimer_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable Forchheimer permeability in quadrature points of a mesh entity.
void get_tortuosity (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant tortuosity in quadrature points of a mesh entity.
void get_tortuosity (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable tortuosity in quadrature points of a mesh entity.
virtual void print_layer_properties () const
This member function is a virtual class that can be used to output to screen information from the layer.
void effective_gas_diffusion_coefficient (const FuelCellShop::Material::PureGas *solute_gas, const FuelCellShop::Material::PureGas *solvent_gas, const SolutionVariable &T_in, const SolutionVariable &p_in, std::vector< double > &D_b) const
Member function used to compute diffusionfor a solute_gas, solvent_gas combination at a given temperature and pressure using the Bousinesq approximation is used in order to compute the bulk combined diffusivity such that
where is the molecular diffusion coefficient obtained using effective_molecular_gas_diffusion_coefficient and is the Knudsen diffusivity computed using Knudsen_diffusion.
void effective_gas_diffusion_coefficient (const FuelCellShop::Material::PureGas *solute_gas, const FuelCellShop::Material::PureGas *solvent_gas, const SolutionVariable &T_in, const SolutionVariable &p_in, std::vector< double > &D_b, std::vector< double > &dD_b_dT) const
Member function used to compute diffusion and its derivative for a solute_gas, solvent_gas combination at a given temperature and pressure using the Bousinesq approximation is used in order to compute the bulk combined diffusivity such that
where is the molecular diffusion coefficient obtained using effective_molecular_gas_diffusion_coefficient and is the Knudsen diffusivity computed using Knudsen_diffusion.
void effective_molecular_gas_diffusion_coefficient (const FuelCellShop::Material::PureGas *solute_gas, const FuelCellShop::Material::PureGas *solvent_gas, const SolutionVariable &T_in, const SolutionVariable &p_in, std::vector< double > &D_m) const
Member function used to compute molecular diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
void effective_molecular_gas_diffusion_coefficient (const FuelCellShop::Material::PureGas *solute_gas, const FuelCellShop::Material::PureGas *solvent_gas, const SolutionVariable &T_in, const SolutionVariable &p_in, std::vector< double > &D_m, std::vector< double > &dD_m_dT) const
Member function used to compute molecular diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
void Knudsen_diffusion (const FuelCellShop::Material::PureGas *solute_gas, const SolutionVariable &T_in, std::vector< double > &D_k) const
Member function used to compute the Knudsen diffusivity in the layer.
void Knudsen_diffusion (const FuelCellShop::Material::PureGas *solute_gas, const SolutionVariable &T_in, std::vector< double > &D_k, std::vector< double > &dD_k_dT) const
Member function used to compute the Knudsen diffusivity in the layer.
Public Member Functions inherited from FuelCellShop::Layer::BaseLayer< dim >
void set_position (const std::vector< Point< dim > > &p)
Member function used by some applications such as dummyGDL in order to know which value to return.
void set_local_material_id (const unsigned int &id)
Function for setting local material id, for unit testing purposes.
void unset_local_material_id ()
Function for unsetting local material id, so that it isn't incorrectly used later Once the key is "unset" to some invalid value, an error will be thrown if the key is requested again without being set.
bool belongs_to_material (const unsigned int material_id)
Check if a given cell belongs to the catalyst layer and assign.
const std::string & name_layer () const
Return the name of the layer.
virtual bool test_layer ()
This virtual class should be used for any derived class to be able to test the functionality of the class.
std::vector< unsigned int > get_material_ids ()
Return the local material id of the layer.
unsigned int local_material_id () const
Return the local material id of the layer, performs a check.
Static Public Member Functions
Instance Delivery (Functions)
static void declare_CatalystLayer_parameters (const std::string &cl_section_name, ParameterHandler &param)
Function used to declare all the data necessary in the parameter files former all CatalystLayer children.
static boost::shared_ptr
< FuelCellShop::Layer::CatalystLayer
< dim > > create_CatalystLayer (const std::string &cl_section_name, ParameterHandler &param)
Function used to select the appropriate CatalystLayer type as specified in the ParameterHandler under line.
Protected Types
Instance Delivery (Types)
typedef std::map< std::string,
CatalystLayer< dim > * > _mapFactory
This object is used to store all objects of type CatalystLayer.
Protected Member Functions
Constructors, destructor, and initalization
CatalystLayer ()
~CatalystLayer ()
Destructor.
CatalystLayer (const std::string &name)
Constructor.
virtual void declare_parameters (const std::string &name, ParameterHandler &param) const
Default virtual declare parameters for a parameter file.
void initialize (ParameterHandler &param)
Member function used to read in data and initialize the necessary data to compute the coefficients.
Instance Delivery (Private functions)
virtual boost::shared_ptr
< FuelCellShop::Layer::CatalystLayer
< dim > > create_replica (const std::string &name)
This member function is used to create an object of type gas diffusion layer.
Protected Member Functions inherited from FuelCellShop::Layer::PorousLayer< dim >
PorousLayer (const std::string &name)
Constructor.
PorousLayer ()
Constructor.
PorousLayer (const std::string &name, FuelCellShop::Material::GasMixture &gas_mixture)
Constructor.
virtual ~PorousLayer ()
Destructor.
virtual void declare_parameters (ParameterHandler &param) const
Declare parameters for a parameter file.
void print_caller_name (const std::string &caller_name) const
This function is used to print out the name of another function that has been declared in the scope of this class, but not yet been implemented.
virtual void gas_diffusion_coefficients (Table< 2, double > &) const
Return the molecular diffusivty all the gases assigned to the layer using set_gases_and_compute.
virtual void derivative_gas_diffusion_coefficients (std::vector< Table< 2, double > > &) const
Return the derivative of the molecular diffusion coefficient with respect to the derivative flags for all the gases assigned to the layer using set_gases_and_compute.
Protected Member Functions inherited from FuelCellShop::Layer::BaseLayer< dim >
BaseLayer ()
Constructor.
BaseLayer (const std::string &name)
Constructor.
virtual ~BaseLayer ()
Destructor.
virtual void set_parameters (const std::string &object_name, const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Member function used to change the values in the parameter file for a given list of parameters.
virtual void set_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Set parameters in parameter file.
Static Protected Member Functions
Instance Delivery (Function)
static _mapFactory * get_mapFactory ()
Return the map library that stores all childrens of this class.
Protected Attributes
Internal variables
std::string diffusion_species_name
If CL properties are stored inside the class (e.g.
bool default_materials
If the default materials are used in the layer, this will be set to true.
std::string catalyst_type
Catalyst type from input file.
std::string catalyst_support_type
Catalyst Support type from input file.
std::string electrolyte_type
Electrolyte type from input file.
std::string kinetics_type
Kinetic class type from input file.
std::string PSD_type
PSD class type from input file.
boost::shared_ptr
< FuelCellShop::Material::PolymerElectrolyteBase > electrolyte
Pointer to the electrolyte object created in the application that is used to calculate the properties of the electrolyte in the catalyst layer.
boost::shared_ptr
< FuelCellShop::Material::CatalystSupportBase > catalyst_support
Pointer to the catalyst support object created in the application that is used to calculate the carbon black conductivity in the catalyst layer.
boost::shared_ptr
< FuelCellShop::Material::CatalystBase > catalyst
Pointer to the catalyst object created in the application that is used to store the properties of the catalyst used in the layer.
boost::shared_ptr
< FuelCellShop::Kinetics::BaseKinetics > kinetics
Pointer to a kinetics object.
boost::shared_ptr
< FuelCellShop::MicroScale::BasePSD
< dim > > PSD
unsigned int n_quad
Stores the number of quadrature points in the cell.
std::map< VariableNames,SolutionVariable > solutions
Map storing solution variables.
VariableNames reactant
Name of the reactant which is being solved for in the catalyst layer.
Protected Attributes inherited from FuelCellShop::Layer::PorousLayer< dim >
FuelCellShop::Material::GasMixture * gas_mixture
Gas mixture.
std::vector
< FuelCellShop::Material::PureGas * > gases
Gases inside a porous layer.
bool porosity_is_constant
Variable defining if the porosity is constant.
bool permeability_is_constant
Variable defining if the permeability is constant.
bool tortuosity_is_constant
Variable defining if the tortuosity is constant.
double porosity
User defined constant porosity.
double Knudsen_radius
Parameter used to define Knudsen pore radius.
SymmetricTensor< 2, dim > permeability
User defined constant permeability, m^2.
SymmetricTensor< 2, dim > SQRT_permeability
Square root of user defined constant permeability, m.
SymmetricTensor< 2, dim > permeability_INV
Inverse of user defined constant permeability, 1/m^2.
SymmetricTensor< 2, dim > SQRT_permeability_INV
Inverse of square root of user defined constant permeability, 1/m.
SymmetricTensor< 2, dim > Forchheimer_permeability
User defined constant Forchheimer permeability, 1/m.
SymmetricTensor< 2, dim > tortuosity
User defined constant tortuosity.
std::string diffusion_species_name
If GDL properties are stored inside the class (e.g DummyGDL) then, return the property stored under coefficient_name name.
double temperature
Temperature [K] used to compute gas diffusivity.
double pressure
Total pressure [atm] used to compute gas diffusivity.
SolutionVariable T_vector
Temperature at every quadrature point inside the cell.
SolutionVariable s_vector
Liquid water saturation at every quadrature point inside the cell.
Table< 2, double > D_ECtheory
Tensor of diffusion coefficients – This are computed with setting up the gas so that they do not need to be recomputed all the time.
std::vector< Table< 2, double > > dD_ECtheory_dx
Vector of tensors for the derivative of the diffusion coefficients – This are computed with setting up the gas so that they do not need to be recomputed all the time.
std::vector< double > D_bulk
Vector of bulk diffusion coefficients at every quadrature point inside the cell.
std::vector< double > dD_bulk_dT
Vector of derivative of bulk diffusion coefficients w.r.t temperature, at every quadrature point inside the cell.
Protected Attributes inherited from FuelCellShop::Layer::BaseLayer< dim >
const std::string name
Name of the layer.
std::vector< unsigned int > material_ids
List of material IDs that belong to the layer.
std::vector< Point< dim > > point
Coordinates of the point where we would like to compute the effective properties.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives.
std::map< VariableNames, double > constant_solutions
Map storing values of solution variables constant in a particular application.
Friends
Friend class for Unit Testing
class ::MultiScaleCLTest
Friend class for testing purposes.
Detailed Description
template<int dim>
class FuelCellShop::Layer::CatalystLayer< dim >
Virtual class used to provide the interface for all CatalystLayer children.
No object of type CatalystLayer should ever be created, instead this layer is used to initialize pointers of type CatalystLayer. The class has a database of children such that it will declare all necessary parameters for all children in the input file, read the input file, create the appripriate children and return a pointer to CatalystLayer with the children selected.
All public functions are virtual but the static functions used to declare parameters and to initialize a pointer of CatalystLayer, i.e. declare_all_CatalystLayer_parameters, set_all_CatalystLayer_parameters and create_CatalystLayer.
Usage Details:
In order to create a catalyst layer within an application, the following steps need to be taken.
First, in the application .h file, create a pointer to a CatalystLayer object, i.e.
* boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > CCL;
*
This pointer object will be available anywhere inside the application. Because we do not want to worry about deleting the pointer afterwards, we use a Boost pointer which has its own memory management algorithms. See the Boost website for more information
Once the pointer is available, we need to do three things in the application
Call declare_CatalystLayer_parameters in the application declare_parameters() member function. This member function is used to define all parameters that can be read from the input file
Call create_CatalystLayer and initialize. The former member function will fill the pointer created above with the appropriate catalyst layer you have selected in the input file. Then, initialize reads from the input file all the data from the file in order to setup the object.
The object is ready for use now.
Here is a code example from app_cathode.cc:
* //--------- IN DECLARE_PARAMETERS ------------------------------------------------------
* template <int dim>
* void
* NAME::AppCathode<dim>::declare_parameters(ParameterHandler& param)
* {
*   (...)
*   // Declare section on the input file where all info will be stored. In this case Fuel Cell Data > Cathode catalyst layer
*   FuelCellShop::Layer::CatalystLayer<dim>::declare_CatalystLayer_parameters("Cathode catalyst layer", param);
*   (...)
* }
*
* //--------- IN INITIALIZE ------------------------------------------------------
* template <int dim>
* void
* NAME::AppCathode<dim>::_initialize(ParameterHandler& param)
* {
*   (...)
*   // Initialize layer classes:
*    std::vector< FuelCellShop::Material::PureGas * > gases;
*    gases.push_back(&oxygen);
*    gases.push_back(&nitrogen);
*
*    catalyst.initialize(param);
*    electrolyte.initialize(param);
*    catalyst_support.initialize(param);
*
*    // Create a catalyst layer. When you create the layer, you also specify the type of electrolyte, catalyst support and catalyst in the layer. For example,
*    // a conventional catalyst layer will take a FuelCellShop::Material::Nafion type electrolyte, a FuelCellShop::Material::Carbon support
*    // and a FuelCellShop::Material::Platinum catalyst.
*    CCL = FuelCellShop::Layer::CatalystLayer<dim>::create_CatalystLayer("Cathode catalyst layer", param);
*
*    // Here, I specify the gases that exist in the CCL and their temperature and pressure (based on operating conditions):
*    CCL->set_gases_and_compute(gases, OC.get_pc_atm (), OC.get_T());
*    // Initialise the necessary kinetics parameters in CCL.
*   (...)
* }
*
Member Typedef Documentation
template<int dim> typedef std::map< std::string, CatalystLayer<dim>* > FuelCellShop::Layer::CatalystLayer< dim >::_mapFactory protected
This object is used to store all objects of type CatalystLayer.
This information in then used in layer_generator.h in order to create the correct object depending on the specified concrete type of layer selected such as DummyCL.
Constructor & Destructor Documentation
template<int dim> FuelCellShop::Layer::CatalystLayer< dim >::CatalystLayer () protected
Warning
For internal use only.
Constructor used only to create a prototype. Do not use in general since this will not include the name of the section in the parameter file you need.
template<int dim> FuelCellShop::Layer::CatalystLayer< dim >::~CatalystLayer () protected
Destructor.
template<int dim> FuelCellShop::Layer::CatalystLayer< dim >::CatalystLayer (const std::string & name) protected
Constructor.
Member Function Documentation
template<int dim> static boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > FuelCellShop::Layer::CatalystLayer< dim >::create_CatalystLayer (const std::string & cl_section_name, ParameterHandler & param) inline static
Function used to select the appropriate CatalystLayer type as specified in the ParameterHandler under line.
* set Catalyst layer type = DummyCL
*
current options are [ DummyCL | MultiScaleCL | HomogeneousCL ]
The class will read the appropriate section in the parameter file, i.e. the one with name
Parameters
cl_section_name,create an object of the desired type and return it.
References FuelCellShop::Layer::CatalystLayer< dim >::create_replica(), FuelCellShop::Layer::CatalystLayer< dim >::get_mapFactory(), and FcstUtilities::log.
template<int dim> virtual boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > FuelCellShop::Layer::CatalystLayer< dim >::create_replica (const std::string & name) inline protected virtual
This member function is used to create an object of type gas diffusion layer.
Warning
This class MUST be redeclared in every child.
Reimplemented in FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, FuelCellShop::Layer::DummyCL< dim >, and FuelCellShop::Layer::HomogeneousCL< dim >.
References FcstUtilities::log.
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::create_CatalystLayer().
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::current_density (std::vector< double > &) inline virtual
This member function will use a FuelCellShop::BaseKinetics class in order to compute the current density production in the CL.
Reimplemented in FuelCellShop::Layer::DummyCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, and FuelCellShop::Layer::HomogeneousCL< dim >.
References FcstUtilities::log.
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::current_density().
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::current_density (std::vector< double > & current, std::vector< double > & effectiveness) inline virtual
This member function will use a FuelCellShop::BaseKinetics class in order to compute the current density production in the CL.
First argument is current density, and second is effectiveness at all quadrature points in the cell.
Reimplemented in FuelCellShop::Layer::DummyCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, and FuelCellShop::Layer::HomogeneousCL< dim >.
References FuelCellShop::Layer::CatalystLayer< dim >::current_density().
template<int dim> static void FuelCellShop::Layer::CatalystLayer< dim >::declare_CatalystLayer_parameters (const std::string & cl_section_name, ParameterHandler & param) inline static
Function used to declare all the data necessary in the parameter files former all CatalystLayer children.
This member function should be used instead of declare_parameters() when we want to use a CatalystLayer pointer that selects the type of CL to run at runtime.
Parameters
cl_section_name Name of the section that will encapuslate all the information about the CL
param ParameterHandler object used to store all information about the simulation. Used to read the parameter file.
The parameter file would look as follows:
subsection cl_section_name set Catalyst layer type = DummyCL # Options: DummyCL | HomogeneousCL | MultiScaleCL set Catalyst type = Platinum # Options: Platinum set Catalyst support type = CarbonBlack # Options: CarbonBlack set Electrolyte type = Nafion # Options: Nafion
References FuelCellShop::Layer::CatalystLayer< dim >::get_mapFactory().
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::declare_parameters (const std::string & name, ParameterHandler & param) const protected virtual
Default virtual declare parameters for a parameter file.
Note
This member function must be virtual since it will be accessed via pointers for all children.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, FuelCellShop::Layer::DummyCL< dim >, and FuelCellShop::Layer::HomogeneousCL< dim >.
Referenced by FuelCellShop::Layer::DummyCL< dim >::declare_parameters().
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_current_density (std::map< VariableNames, std::vector< double > > &) inline virtual
This member function will use a FuelCellShop::BaseKinetics class in order to compute the derivative of the current density with respect to the variables setup using set_derivative_flags.
Reimplemented in FuelCellShop::Layer::DummyCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, and FuelCellShop::Layer::HomogeneousCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_dpcapillary_dsat (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of in the CL, with respect to either the solution or design parameters, at all quadrature points in the cell.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags().
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_electron_conductivity (std::vector< double > &) const inline virtual
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_electron_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_gas_diffusivity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const inline virtual
Return the derivative of effective diffusivity w.r.t solution variables/design parameters for nonisothermal with/without two-phase case in the CL.
It transforms bulk diffusion properties computed using compute_gas_diffusion method and transforms it into an effective property, taking into account the porosity, saturation and CL structure (Anisotropic case), at all quadrature points of the cell.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_proton_conductivity (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the effective proton conductivity in the CL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_thermal_conductivity (std::vector< double > &) const inline virtual
Compute the derivative of the effective thermal conductivity in the CL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective thermal conductivity in the CL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_thermoosmotic_diffusivity (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the effective thermo-osmotic diffusivity of lambda (sorbed water) in the CL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_effective_water_diffusivity (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the effective water diffusivity (lambda diffusivity) in the CL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_gas_permeablity (std::vector< double > &) const inline virtual
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_gas_permeablity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_interfacial_surface_area (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the CL.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags().
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::derivative_liquid_permeablity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const inline virtual
Compute the derivative of the anisotropic liquid permeability in the CL with respect to either the solution or design parameters, at all quadrature points in the cell.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::dpcapillary_dsat (std::vector< double > &) const inline virtual
Compute , at all quadrature points in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_electron_conductivity (double &) const inline virtual
Compute the effective electron conductivity in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_electron_conductivity (Tensor< 2, dim > &) const inline virtual
Compute the effective electron conductivity in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_gas_diffusivity (const double & , const double & , double &) const inline virtual
Compute the effective property in the pores of the CL.
This is used for example to compute effective diffusivity of gases. The method takes in bulk diffusion coefficient [m^2/s] and liquid water saturation as the first and second argument respectively. This routine is used in the isotropic case.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_gas_diffusivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Return the effective diffusivity [m^2/s] for nonisothermal with/without two-phase case in the CL.
It takes bulk diffusivity, computed using compute_gas_diffusion method and transforms it into an effective property, taking into account the porosity, saturation and CL structure (Anisotropic case), at all quadrature points of the cell.
Note
: For two-phase case, set_saturation should be called before using this method, otherwise this method assumes saturation value to be zero.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_gas_diffusivity (Table< 2, Tensor< 2, dim > > &) const inline virtual
Compute the effective property in the pores of the CL.
This is used to compute effective diffusivity of gases. This routine can be used either in the isotropic or anisotropic cases. Bulk diffusion coefficients or their derivatives are obtained from Mixure::BinaryDiffusion classes inside this method.
Note
The routine FuelCellShop::Layer::PorousLayer< dim >::set_gases_and_compute (std::vector< FuelCellShop::Material::PureGas * > &gases, double pressure, double temperature) (in the parent class) should have been called prior to using this class. This method is to be used only for a single-phase, isothermal application.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_proton_conductivity (double &) const inline virtual
Compute the effective proton conductivity in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_proton_conductivity (std::vector< double > &) const inline virtual
Compute the effective proton conductivity, at all quadrature points in the cell, mainly as a function of Temperature.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_thermal_conductivity (double &) const inline virtual
Compute the effective thermal conductivity in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_thermal_conductivity (Tensor< 2, dim > &) const inline virtual
Compute the effective thermal conductivity in the CL.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the effective thermal conductivity as a Tensor at all quadrature points.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_thermoosmotic_diffusivity (std::vector< double > &) const inline virtual
Compute the effective thermo-osmotic diffusivity of lambda (sorbed water), at all quadrature points in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_water_diffusivity (double &) const inline virtual
Compute the effective water diffusivity (lambda diffusivity) in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::effective_water_diffusivity (std::vector< double > &) const inline virtual
Compute the effective water diffusivity (lambda diffusivity) at all quadrature points in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::gas_permeablity (double &) const inline virtual
Compute the CL gas permeability.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::gas_permeablity (Tensor< 2, dim > &) const inline virtual
Compute the CL gas permeability.
References FcstUtilities::log.
template<int dim> virtual double FuelCellShop::Layer::CatalystLayer< dim >::get_active_area_Pt () const inline virtual
Get the active area of platinum per unit volume of CL.
Reimplemented in FuelCellShop::Layer::DummyCL< dim >, and FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> const std::type_info& FuelCellShop::Layer::CatalystLayer< dim >::get_base_type () const inline virtual
This member function returns a type_info object with the name of the base layer type the inherited class belongs to, i.e.
GasDiffusionLayer
MicroPorousLayer
CatalystLayer
MembraneLayer
SolidLayer
Channel
Note that this is necessary if we want to find out not the name of the actual class which can be obtain using
const std::type_info& name = typeid(*this)
but the name of the parent class.
Note
Do not re-implement this class in children classes
Reimplemented from FuelCellShop::Layer::BaseLayer< dim >.
template<int dim> virtual SolutionMap FuelCellShop::Layer::CatalystLayer< dim >::get_coverages () virtual
Method for getting coverages from kinetics objects (overloaded by MultiScaleCL)
Reimplemented in FuelCellShop::Layer::MultiScaleCL< dim >, and FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >.
template<int dim> virtual FuelCellShop::Material::PolymerElectrolyteBase* FuelCellShop::Layer::CatalystLayer< dim >::get_electrolyte () const inline virtual
Method to provide access to pointer of the electrolyte object of the catalyst layer.
References FuelCellShop::Layer::CatalystLayer< dim >::electrolyte.
Referenced by FuelCellShop::PostProcessing::WaterSorptionResponse< dim >::compute_responses().
template<int dim> virtual FuelCellShop::Kinetics::BaseKinetics* FuelCellShop::Layer::CatalystLayer< dim >::get_kinetics () const inline virtual
Method to provide access to pointer of the kinetic object of the catalyst layer.
References FuelCellShop::Layer::CatalystLayer< dim >::kinetics.
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::get_kinetics_type () inline
Method for getting string describing kinetics type (corresponding to kinetics class concrete names)
References FuelCellShop::Layer::CatalystLayer< dim >::kinetics_type.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::get_loadings (std::map< std::string, double > &) inline virtual
Return loadings.
Parameters
V_Pt = Pt loading in ug/cm3
Parameters
loading_N = ionomer loading wt
Parameters
IC_ratio = I/C ratio
Note
either loading_N or IC_ratio should be passed through input file, the other computed
Parameters
prc_Pt = Pt/C ratio
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> static _mapFactory* FuelCellShop::Layer::CatalystLayer< dim >::get_mapFactory () inline static protected
Return the map library that stores all childrens of this class.
The declare_parameters of each one of the children that are in the map are called in declare_all_CatalystLayers.
Warning
In order for children of this class to appear in the map the following four things are necessary
a static PROTOTYPE object has to be created. For example, in the .h file:
* static DummyCL<dim> const* PROTOTYPE;
*
in the .cc file:
* template <int dim>
* NAME::DummyCL<dim> const* NAME::DummyCL<dim>::PROTOTYPE = new NAME::DummyCL<dim>();
*
a default constructor which creates the PROTOTYPE is needed, e.g.
* template <int dim>
* NAME::DummyCL<dim>::DummyCL()
* : FuelCellShop::Layer::CatalystLayer<dim> ()
* {
*    FcstUtilities::log<<" Register DummyGDL GDL to FactoryMap"<<std::endl;
*    this->get_mapFactory()->insert(std::pair<std::string, FuelCellShop::Layer::GasDiffusionLayer<dim>* >(concrete_name, this));
* }
*
a static std::string concrete_name must be declared and initialized to the desired name of the children class. This name is used as the name in the map and as the name of the subsection where its parameters are declared. For example, in the .h file:
* static const std::string concrete_name;
*
in the .cc file:
* template <int dim>
* const std::string NAME::DummyCL<dim>::concrete_name ("DummyCL");
*
virtual boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > create_replica () needs to be re-implemented in the child. For example, in the .h file
* virtual boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > create_replica (std::string &name,
*                                                                                     FuelCellShop::Material::PolymerElectrolyteBase* electrolyte1,
*                                                                                     FuelCellShop::Material::CatalystSupportBase* catalyst_support1,
*                                                                                     FuelCellShop::Material::CatalystBase* catalyst1)
* {
*   return boost::shared_ptr<FuelCellShop::Layer::CatalystLayer<dim> > (new FuelCellShop::Layer::DummyCL<dim> (name, electrolyte1, catalyst_support1, catalyst1));
* }
*
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::create_CatalystLayer(), and FuelCellShop::Layer::CatalystLayer< dim >::declare_CatalystLayer_parameters().
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::get_volume_fractions (std::map< std::string, double > &) inline virtual
Compute the volume fractions of each phase.
The map might contains a string indicating the phase and its value. There are several possible phases:
Solid
Void
Ionomer
Water
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> void FuelCellShop::Layer::CatalystLayer< dim >::initialize (ParameterHandler & param) protected virtual
Member function used to read in data and initialize the necessary data to compute the coefficients.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >, FuelCellShop::Layer::HomogeneousCL< dim >, and FuelCellShop::Layer::DummyCL< dim >.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::interfacial_surface_area (std::vector< double > &) const inline virtual
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the CL.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::liquid_permeablity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the anisotropic CL liquid permeability , at all quadrature points in the cell.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::pcapillary (std::vector< double > &) const inline virtual
Compute , at all quadrature points in the cell.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::ConventionalCL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::set_cell_id (const unsigned int & id) inline virtual
Function for setting current cell_id from applications.
Parameters
unsigned int id is the id of the current cell from the application's perspective
Note
Reimplemented by classes that need to know cell_id: MultiScaleCL
Reimplemented in FuelCellShop::Layer::HomogeneousCL< dim >, FuelCellShop::Layer::DummyCL< dim >, FuelCellShop::Layer::MultiScaleCL< dim >, and FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::set_constant_solution (const double & value, const VariableNames & name) inline virtual
Set those solution variables which are constant in the particular application.
If the effective properties in the layer depend on other variables that are usually part of the solution vector but are assumed to be constant in this simulation, the const solution value should be passed to the class using this member function. This method should be called in the initialization section of the application. This function takes value to be set as the first argument and the VariableNames as second argument. For instance, it's required to store constant temperature value for an isothermal application, in that case this method can be used. e.g., in order to set temperature as 353.0 [Kelvin] in the layer, you can use the following code:
* // In the initialization section of the application.
* layer.set_constant_solution(353.0, VariableNames::temperature_of_REV);
*
If temperature_of_REV is passed using this method, it also sets the temperature [Kelvin] values in the electrolyte object. If total_pressure is passed using this method, it also sets the total pressure [Pascals] values in the kinetics and electrolyte object.
Reimplemented from FuelCellShop::Layer::BaseLayer< dim >.
References FuelCellShop::Layer::CatalystLayer< dim >::electrolyte, FuelCellShop::Layer::CatalystLayer< dim >::kinetics, membrane_water_content, FuelCellShop::Layer::BaseLayer< dim >::set_constant_solution(), temperature_of_REV, and total_pressure.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::set_derivative_flags (const std::vector< VariableNames > & flags) inline virtual
Method used to set the variables for which you would like to compute the derivatives in the catalyst layer.
It takes vector of VariableNames as an input argument. It also sets the derivative flags in the kinetics and electrolyte object of the catalyst layer.
Reimplemented from FuelCellShop::Layer::BaseLayer< dim >.
References FuelCellShop::Layer::BaseLayer< dim >::derivative_flags, FuelCellShop::Layer::CatalystLayer< dim >::electrolyte, and FuelCellShop::Layer::CatalystLayer< dim >::kinetics.
template<int dim> void FuelCellShop::Layer::CatalystLayer< dim >::set_reaction_kinetics (const ReactionNames rxn_name) inline
Member function used to specify the reaction for which the kinetic parameters are needed, for example for a Platinum catalyst, we can specify that we need the kinetic parameters for either the oxygen reduction reaction (ORR) or the hydrogen oxidation reaction (HOR)
References FuelCellShop::Layer::CatalystLayer< dim >::catalyst, and FuelCellShop::Layer::CatalystLayer< dim >::kinetics.
template<int dim> virtual void FuelCellShop::Layer::CatalystLayer< dim >::set_solution (const std::vector< SolutionVariable > &) virtual
This method is used to set the solution variable values in the kinetics object, at all quadrature points in the cell.
It takes vector of SolutionVariable structures as input argument. Each one of them corresponds to a particular solution variable, required in order to compute various terms such as non-linear current source terms etc.
Note
Use only for solution variables.
Reimplemented from FuelCellShop::Layer::BaseLayer< dim >.
Friends And Related Function Documentation
template<int dim> friend class ::MultiScaleCLTest friend
Friend class for testing purposes.
Member Data Documentation
template<int dim> boost::shared_ptr< FuelCellShop::Material::CatalystBase > FuelCellShop::Layer::CatalystLayer< dim >::catalyst protected
Pointer to the catalyst object created in the application that is used to store the properties of the catalyst used in the layer.
Referenced by FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >::get_resource(), and FuelCellShop::Layer::CatalystLayer< dim >::set_reaction_kinetics().
template<int dim> boost::shared_ptr< FuelCellShop::Material::CatalystSupportBase > FuelCellShop::Layer::CatalystLayer< dim >::catalyst_support protected
Pointer to the catalyst support object created in the application that is used to calculate the carbon black conductivity in the catalyst layer.
Referenced by FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >::get_resource().
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::catalyst_support_type protected
Catalyst Support type from input file.
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::catalyst_type protected
Catalyst type from input file.
template<int dim> bool FuelCellShop::Layer::CatalystLayer< dim >::default_materials protected
If the default materials are used in the layer, this will be set to true.
If the materials are created in the application and passed down this will be false. Used for the destructor.
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::diffusion_species_name protected
If CL properties are stored inside the class (e.g.
DummyCL) then, return the property stored under coefficient_name name
template<int dim> boost::shared_ptr< FuelCellShop::Material::PolymerElectrolyteBase > FuelCellShop::Layer::CatalystLayer< dim >::electrolyte protected
Pointer to the electrolyte object created in the application that is used to calculate the properties of the electrolyte in the catalyst layer.
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::get_electrolyte(), FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >::get_resource(), FuelCellShop::Layer::CatalystLayer< dim >::set_constant_solution(), and FuelCellShop::Layer::CatalystLayer< dim >::set_derivative_flags().
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::electrolyte_type protected
Electrolyte type from input file.
template<int dim> boost::shared_ptr< FuelCellShop::Kinetics::BaseKinetics > FuelCellShop::Layer::CatalystLayer< dim >::kinetics protected
Pointer to a kinetics object.
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::get_kinetics(), FuelCellShop::Layer::MultiScaleCL< deal_II_dimension >::get_resource(), FuelCellShop::Layer::CatalystLayer< dim >::set_constant_solution(), FuelCellShop::Layer::CatalystLayer< dim >::set_derivative_flags(), and FuelCellShop::Layer::CatalystLayer< dim >::set_reaction_kinetics().
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::kinetics_type protected
Kinetic class type from input file.
Referenced by FuelCellShop::Layer::CatalystLayer< dim >::get_kinetics_type().
template<int dim> unsigned int FuelCellShop::Layer::CatalystLayer< dim >::n_quad protected
Stores the number of quadrature points in the cell.
template<int dim> boost::shared_ptr< FuelCellShop::MicroScale::BasePSD<dim> > FuelCellShop::Layer::CatalystLayer< dim >::PSD protected
template<int dim> std::string FuelCellShop::Layer::CatalystLayer< dim >::PSD_type protected
PSD class type from input file.
template<int dim> VariableNames FuelCellShop::Layer::CatalystLayer< dim >::reactant protected
Name of the reactant which is being solved for in the catalyst layer.
This is specifically used by the FuelCellShop::Layer::MultiScaleCL<dim> object.
template<int dim> std::map<VariableNames ,SolutionVariable> FuelCellShop::Layer::CatalystLayer< dim >::solutions protected
Map storing solution variables.
Key represents the name of the variable and Value represents the FuelCellShop::SolutionVariable structure.
The documentation for this class was generated from the following file:
catalyst_layer.h