OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Material::LiquidWater Class Reference
FuelCellShop::Material::LiquidWater Class Reference
LiquidWater as a publicly derived class of Pureliquid.
#include <PureLiquid.h>
Public Member Functions
LiquidWater ()
virtual ~LiquidWater ()
virtual char * get_name ()
virtual char * get_formula ()
void declare_parameters (ParameterHandler &param) const
Declare all necessary parameters in order to compute the coefficients.
void initialize (ParameterHandler &param)
Member function used to read in data and initialize the necessary data to compute the coefficients.
double get_DO2 ()
double get_DH ()
double get_Relative_Permittivity ()
double get_molecular_width ()
Return the width of a water molecule in .
double get_HO2 ()
Return the Henery's constant for oxygen in water .
Public Member Functions inherited from FuelCellShop::Material::PureLiquid
PureLiquid ()
Constructor.
virtual ~PureLiquid ()
Destructor.
Public Member Functions inherited from FuelCellShop::Material::BaseMaterial
void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the names of FCST solution variables with respect to which you would like to compute the derivatives of material properties.
const std::string & name_material () const
Return the name of the layer.
virtual void print_material_properties () const
This function prints out the material properties.
Static Public Member Functions
static double get_density ()
Return the density of liquid water in .
static double latentVap_heat (const double &)
Static function to return latent heat of vaporization of water as a function of input temperature .
static double surface_tension (const double &)
Static function to return surface tension of liquid water as a function of input temperature .
static double deriv_latentVap_heat (const double &)
Static function to return derivative of latent heat of vaporization of water with respect to temperature , as a function of input temperature .
static double viscosity (const double &)
Static function to return viscosity of water as a function of input temperature .
static double deriv_viscosity (const double &)
Static function return derivative of viscosity of water with respect to temperature, , as a function of input temperature .
Private Attributes
double oxygen_diffusion_coeff
double proton_diffusion_coeff
double relative_permittivity
double molecular_width
double HenryO2
Additional Inherited Members
Public Attributes inherited from FuelCellShop::Material::PureLiquid
double M
Molar mass in g/mol or kg/kmol.
double Mu_0
dynamic viscosity at STP
Protected Member Functions inherited from FuelCellShop::Material::BaseMaterial
BaseMaterial ()
Constructor.
BaseMaterial (const std::string &name)
Constructor.
virtual ~BaseMaterial ()
Destructor.
Protected Attributes inherited from FuelCellShop::Material::BaseMaterial
const std::string name
Name of the layer.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives of material properties.
Detailed Description
LiquidWater as a publicly derived class of Pureliquid.
Constructor & Destructor Documentation
FuelCellShop::Material::LiquidWater::LiquidWater ()
virtual FuelCellShop::Material::LiquidWater::~LiquidWater () virtual
Member Function Documentation
void FuelCellShop::Material::LiquidWater::declare_parameters (ParameterHandler & param) const virtual
Declare all necessary parameters in order to compute the coefficients.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Referenced by FuelCellShop::MicroScale::HybridAgglomerate::declare_parameters(), and FuelCellShop::MicroScale::WaterAgglomerate::declare_parameters().
static double FuelCellShop::Material::LiquidWater::deriv_latentVap_heat (const double &) static
Static function to return derivative of latent heat of vaporization of water with respect to temperature , as a function of input temperature .
Ref: Simple Forumulas for Thermophysical Properties of Liquid Water for Heat Transfer Calculations (from 0C to 150C), C. O. Popiel and K. Wojtkowiak, Heat Transfer Engineering, Vol.19, No.3, 1998.
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters().
static double FuelCellShop::Material::LiquidWater::deriv_viscosity (const double &) static
Static function return derivative of viscosity of water with respect to temperature, , as a function of input temperature .
Ref: Fox R. W and McDonald A. T., Introduction to Fluid Mechanics. John Wiley & Sons, Inc., New York, fifth edition, 1998.
static double FuelCellShop::Material::LiquidWater::get_density () inline static
Return the density of liquid water in .
double FuelCellShop::Material::LiquidWater::get_DH () inline
double FuelCellShop::Material::LiquidWater::get_DO2 () inline
virtual char* FuelCellShop::Material::LiquidWater::get_formula () virtual
Implements FuelCellShop::Material::PureLiquid.
double FuelCellShop::Material::LiquidWater::get_HO2 () inline
Return the Henery's constant for oxygen in water .
double FuelCellShop::Material::LiquidWater::get_molecular_width () inline
Return the width of a water molecule in .
virtual char* FuelCellShop::Material::LiquidWater::get_name () virtual
Implements FuelCellShop::Material::PureLiquid.
double FuelCellShop::Material::LiquidWater::get_Relative_Permittivity () inline
void FuelCellShop::Material::LiquidWater::initialize (ParameterHandler & param) virtual
Member function used to read in data and initialize the necessary data to compute the coefficients.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Referenced by FuelCellShop::MicroScale::HybridAgglomerate::initialize(), and FuelCellShop::MicroScale::WaterAgglomerate::initialize().
static double FuelCellShop::Material::LiquidWater::latentVap_heat (const double &) static
Static function to return latent heat of vaporization of water as a function of input temperature .
Ref: Simple Forumulas for Thermophysical Properties of Liquid Water for Heat Transfer Calculations (from 0C to 150C), C. O. Popiel and K. Wojtkowiak, Heat Transfer Engineering, Vol.19, No.3, 1998.
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters().
static double FuelCellShop::Material::LiquidWater::surface_tension (const double &) static
Static function to return surface tension of liquid water as a function of input temperature .
Ref: International Tables of the surface tension of water N.B. Vargaftik,
static double FuelCellShop::Material::LiquidWater::viscosity (const double &) static
Static function to return viscosity of water as a function of input temperature .
Ref: Fox R. W and McDonald A. T., Introduction to Fluid Mechanics. John Wiley & Sons, Inc., New York, fifth edition, 1998.
Member Data Documentation
double FuelCellShop::Material::LiquidWater::HenryO2 private
double FuelCellShop::Material::LiquidWater::molecular_width private
double FuelCellShop::Material::LiquidWater::oxygen_diffusion_coeff private
double FuelCellShop::Material::LiquidWater::proton_diffusion_coeff private
double FuelCellShop::Material::LiquidWater::relative_permittivity private
The documentation for this class was generated from the following file:
PureLiquid.h