OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Equation::LiquidSourceEquation< dim > Class Template Reference
FuelCellShop::Equation::LiquidSourceEquation< dim > Class Template Reference
This class implements a liquid water condensation and evaporation term.
#include <liquid_water_source_terms.h>
Public Member Functions
Constructors, destructor, and initalization
LiquidSourceEquation (FuelCell::SystemManagement &system_management, boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData > data=boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData >())
Constructor.
virtual ~LiquidSourceEquation ()
Destructor.
virtual void declare_parameters (ParameterHandler &param) const
Declare parameters.
virtual void initialize (ParameterHandler &param)
Initialize parameters.
Local CG FEM based assemblers
virtual void assemble_cell_matrix (FuelCell::ApplicationCore::MatrixVector &cell_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local cell matrix.
virtual void assemble_cell_residual (FuelCell::ApplicationCore::FEVector &cell_rhs, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local cell residual.
Accessors and info
virtual void print_equation_info () const
The function prints out the equation's info about the internal coupling equations with the liquid water source terms.
double get_kevap () const
Returns evaporation rate constant, .
double get_kcond () const
Returns condensation rate constant, .
void set_relative_humility (double const x_wv)
Set the relative humility value from the operating condition class (using get_x_wv)
virtual void adjust_internal_cell_couplings (std::vector< couplings_map > &) const
This function is used to adjust std::vector < internal_cell_couplings >, which is generated after getting internal_cell_couplings from all the equations being used in the application.
Public Member Functions inherited from FuelCellShop::Equation::EquationBase< dim >
virtual void assemble_bdry_matrix (FuelCell::ApplicationCore::MatrixVector &bdry_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local boundary matrix.
virtual void assemble_bdry_residual (FuelCell::ApplicationCore::FEVector &bdry_residual, const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local boundary residual.
const couplings_map & get_internal_cell_couplings () const
This function returns internal_cell_couplings of a derived equation class.
const couplings_map & get_internal_flux_couplings () const
This function returns internal_flux_couplings (DG FEM only) of a derived equation class.
const
component_materialID_value_map & get_component_materialID_value () const
This function returns component_materialID_value of a derived equation class.
const
component_boundaryID_value_map & get_component_boundaryID_value () const
This function returns component_boundaryID_value of a derived equation class.
const std::vector< BoundaryType > & get_boundary_types () const
This function returns boundary_types of a derived equation class.
const std::vector< std::vector
< BoundaryType > > & get_multi_boundary_types () const
This function returns multi_boundary_types of a derived equation class.
const std::vector< OutputType > & get_output_types () const
This function returns output_types of a derived equation class.
const std::vector< std::vector
< OutputType > > & get_multi_output_types () const
This function returns multi_output_types of a derived equation class.
const std::string & get_equation_name () const
This function returns equation_name of a derived equation class.
const std::vector< unsigned int > & get_matrix_block_indices () const
This function returns matrix_block_indices of a derived equation class.
const std::vector< unsigned int > & get_residual_indices () const
This function returns residual_indices of a derived equation class.
Protected Member Functions
void get_temp_related_parameters (double Temp, double c_pressure, double &psat, double &dpsat_dT, double &h_lv, double &dhlv_dT, double &Kelvin_factor, double &psat_kelvin, double &dpsat_kelvin_dpc, double &dpsat_kelvin_dT, FuelCellShop::Material::WaterVapor water) const
Inline function to reduce the repeatability of the code This function is used to compute Kelvin saturation pressure, latent heat of water and all the derivates with respect to Kelvin saturation pressure.
Local CG FEM based assemblers - make_ functions
virtual void make_assemblers_generic_constant_data ()
This function computes Local CG FEM based assemblers - constant data (generic).
virtual void make_assemblers_cell_constant_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info)
This function computes Local CG FEM based assemblers - constant data (cell) and allocates the memory for shape functions, shape function gradients, and JxW_cell in Local CG FEM based assemblers - variable data (cell) .
virtual void make_assemblers_cell_variable_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
This function computes Local CG FEM based assemblers - variable data (cell) .
Other make_ functions
virtual void make_boundary_types ()
This function fills out boundary_types.
virtual void make_output_types ()
This function fills out output_types.
Protected Member Functions inherited from FuelCellShop::Equation::EquationBase< dim >
EquationBase (FuelCell::SystemManagement &sys_management, boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData > data=boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData >())
Constructor.
virtual ~EquationBase ()
Destructor.
virtual void set_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Set parameters using the parameter file, in order to run parametric/optimization studies.
virtual void make_assemblers_bdry_constant_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info)
virtual void make_assemblers_bdry_variable_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
void select_cell_assemblers (const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
This routine is used to select the make_assembly routines that need to be called inside assemble_cell_matrix to compute.
virtual void make_internal_cell_couplings ()
This function fills out internal_cell_couplings of a derived equation class.
virtual void make_internal_flux_couplings ()
This function fills out internal_flux_couplings (DG FEM only) of a derived equation class.
virtual void make_component_materialID_value ()
This function fills out component_materialID_value of a derived equation class.
virtual void make_component_boundaryID_value ()
This function fills out component_boundaryID_value of a derived equation class.
virtual void make_multi_boundary_types ()
This function fills out multi_boundary_types of a derived equation class.
virtual void make_multi_output_types ()
This function fills out multi_output_types of a derived equation class.
virtual void make_matrix_block_indices ()
This function is only needed to provide the last argument to dealII_to_appframe.
virtual void make_residual_indices ()
This function is only needed to provide the last argument to dealII_to_appframe.
virtual void assemble_cell_Jacobian_matrix (FuelCell::ApplicationCore::MatrixVector &cell_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble the local Jacobian Matrix for Non-Linear problems.
virtual void assemble_bdry_Jacobian_matrix (FuelCell::ApplicationCore::MatrixVector &bdry_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local Jacobian boundary matrix for Non-Linear problems.
virtual void assemble_cell_linear_matrix (FuelCell::ApplicationCore::MatrixVector &cell_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble the local cell matrix for Linear problems.
virtual void assemble_cell_residual_rhs (FuelCell::ApplicationCore::FEVector &cell_residual, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local cell RHS for nonlinear problems.
virtual void assemble_cell_linear_rhs (FuelCell::ApplicationCore::FEVector &cell_residual, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo &cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local cell RHS for Linear problems.
virtual void assemble_bdry_linear_matrix (FuelCell::ApplicationCore::MatrixVector &bdry_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local boundary matrix for linear problems.
virtual void assemble_bdry_linear_rhs (FuelCell::ApplicationCore::FEVector &bdry_residual, const typename FuelCell::ApplicationCore::DoFApplication< dim >::FaceInfo &bdry_info, FuelCellShop::Layer::BaseLayer< dim > *const layer)
Assemble local boundary RHS for linear problems.
void standard_to_block_wise (FullMatrix< double > &target) const
This function changes the order of dealii::FullMatrix<double> target from standard to block-wise.
void standard_to_block_wise (Vector< double > &target) const
This function changes the order of dealii::Vector<double> target from standard to block-wise.
void dealII_to_appframe (FuelCell::ApplicationCore::MatrixVector &dst, const FullMatrix< double > &src, const std::vector< unsigned int > &matrix_block_indices) const
This function converts the standard ordered structure dealii::FullMatrix<double> src into the block-wise ordered structure FuelCell::ApplicationCore::MatrixVector dst.
void dealII_to_appframe (FuelCell::ApplicationCore::FEVector &dst, const Vector< double > &src, const std::vector< unsigned int > &residual_indices) const
This function converts the standard ordered structure dealii::Vector<double> src into the block-wise ordered structure FuelCell::ApplicationCore::FEVector dst.
bool belongs_to_boundary (const unsigned int &tria_boundary_id, const unsigned int &param_boundary_id) const
This function returns true if a boundary indicator of an external face on the triangulation coincides with a boundary indicator defined in the parameters file of a derived equation class.
void print_caller_name (const std::string &caller_name) const
This function is used to print out the name of another function that has been declared in the scope of this class, but not yet been implemented.
Protected Attributes
bool cell_residual_counter
Counter set to TRUE when cell_residual is being assembled.
unsigned int last_iter_cell
Variable used to store the index in cell_info->global_data of the previous Newton solution The solution at the previous iteration is used to compute cell_matrix and cell_residual.
double T_constant
This tempearture is used when not solving temperature as the solution variable.
double Relative_humility
This is used to return relative humility the when not solving water vapor as the solution variable.
bool Relative_humility_is_set
This is used to check if relative humility is set when not solving water vapor as the solution variable.
Generic Constant Data
std::map< unsigned int, double > capillary_pressure_current_flux_map
VariableInfo p_liquid_water
VariableInfo structure corresponding to "liquid_capillary_pressure".
VariableInfo x_water
VariableInfo structure corresponding to "water_molar_fraction".
VariableInfo t_rev
VariableInfo structure corresponding to "temperature_of_REV".
unsigned int fickswater_blockindex_xwater
Block index for "water_molar_fraction" corresponding to "Ficks Transport Equation - water".
unsigned int fickswater_blockindex_pliquid
Block index for "liquid_capillary_pressure" corresponding to "Ficks Transport Equation - water".
unsigned int fickswater_blockindex_trev
Block index for "temperature_of_REV" corresponding to "Ficks Transport Equation - water".
unsigned int thermal_blockindex_xwater
Block index for "water_molar_fraction" corresponding to "Thermal Transport Equation".
unsigned int thermal_blockindex_pliquid
Block index for "liquid_capillary_pressure" corresponding to "Thermal Transport Equation".
unsigned int thermal_blockindex_trev
Block index for "temperature_of_REV" corresponding to "Thermal Transport Equation".
double M_water
Molar weight of water in grams/mole.
double k_e
Evaporation rate constant, .
double k_c
Condensation rate constant, .
double rho_l
Density of liquid water, .
Local CG FEM based assemblers - variable data (cell)
double p_cell
Total pressure in the cell.
std::vector< double > area_lv_cell
Interfacial surface area per unit volume, , at all quadrature points in the cell.
std::vector< double > darea_lv_dp_cell
, at all quadrature points in the cell.
std::vector< std::vector
< double > > phi_p_cell
shape functions.
std::vector< std::vector
< double > > phi_xwater_cell
shape functions.
std::vector< std::vector
< double > > phi_T_cell
shape functions.
Protected Attributes inherited from FuelCellShop::Equation::EquationBase< dim >
unsigned int dofs_per_cell
Number of degrees of freedom per cell.
unsigned int n_q_points_cell
Number of quadrature points per cell.
unsigned int n_q_points_bdry
Number of quadrature points per boundary.
DoFHandler< dim >
::active_cell_iterator cell
Currently active DoFHandler<dim> active cell iterator.
DoFHandler< dim >
::active_face_iterator bdry
Currently active DoFHandler<dim> active boundary iterator.
std::vector< double > JxW_cell
Jacobian of mapping by Weight in the quadrature points of a cell.
std::vector< double > JxW_bdry
Jacobian of mapping by Weight in the quadrature points of a boundary.
std::vector< Point< dim > > normal_vectors
Normal vectors in the quadrature points of a boundary.
std::vector< std::vector
< Point< dim > > > tangential_vectors
Tangential vectors in the quadrature points of a boundary.
FuelCell::SystemManagement * system_management
Pointer to the external YourApplication<dim>::system_management object.
couplings_map internal_cell_couplings
This object contains the info on how the equations and solution variables of a derived equation class are coupled.
couplings_map internal_flux_couplings
This object contains the info on how the "X" and "Y" of a derived equation class are coupled (DG FEM only).
component_materialID_value_map component_materialID_value
This object reflects the following structure (see FuelCell::InitialAndBoundaryData namespace docs):
component_boundaryID_value_map component_boundaryID_value
This object reflects the following structure (see FuelCell::InitialAndBoundaryData namespace docs):
std::vector< BoundaryType > boundary_types
The list of boundary types of a derived equation class.
std::vector< std::vector
< BoundaryType > > multi_boundary_types
The list of multiple boundary types of a derived equation class.
std::vector< OutputType > output_types
The list of output types of a derived equation class.
std::vector< std::vector
< OutputType > > multi_output_types
The list of multiple output types of a derived equation class.
std::string equation_name
The name of a derived equation class.
std::string name_base_variable
Const std::string member storing name of the base solution variable corresponding to the equation represented by this class.
std::vector< unsigned int > matrix_block_indices
The system matrix block indices (a derived equation class) drawn from the global structure (a derived equation class + other active equation classes included into the computation).
std::vector< unsigned int > residual_indices
The residual indices (a derived equation class) drawn from the global structure (a derived equation class + other active equation classes included into the computation).
std::vector< bool > counter
This vector contains the collection of internal "counters" used by the derived equation classes.
EquationFlags assemble_flags
This vector contains a collection of internal flags to tell derived equation classes what needs to be re-computed.
boost::shared_ptr
< FuelCell::ApplicationCore::ApplicationData > data
Data object for the application data to be passed to the equation classes.
std::string solution_vector_name
The name of the solution vector in FEVectors.
std::string residual_vector_name
The name of the residual vector name in FEVectors.
Additional Inherited Members
Public Attributes inherited from FuelCellShop::Equation::EquationBase< dim >
bool variable_initial_data
true, if variable initial data is prescribed on a part of the domain.
bool variable_boundary_data
true, if variable Dirichlet boundary conditions are prescribed on a part of the boundary.
Detailed Description
template<int dim>
class FuelCellShop::Equation::LiquidSourceEquation< dim >
This class implements a liquid water condensation and evaporation term.
It is to be noted that this equation is suggested to be solved alongside Thermal Transport Equation and Ficks Transport Equation - water. Thus these two equations are necessary while considering this equation class.
It is solved with respect to:
(capillary_pressure), (Temperature) and (water_molar_fraction)
This equation can be written as:
is the evaporation-condensation (phase change) rate constant .
is the liquid-vapour interfacial surface area per unit volume .
is the molar weight of water .
is water vapour partial pressure , which is a function of water_molar_fraction, .
is the saturation pressure . This value is a function of (temperature_of_REV), .
is the latent heat of phase change.
Remarks
There is no provision to specify boundary indicators for No liquid water flux or Symmetric boundary conditions, as FEM formulation automatically implies a particular boundary is one of these cases, by default.
This class works with the following layer classes only:
FuelCellShop::Layer::GasDiffusionLayer<dim>
FuelCellShop::Layer::MicroPorousLayer<dim>
FuelCellShop::Layer::CatalystLayer<dim>
We solve the whole problem by linearizing the governing equation at each Newton iteration with subsequent CG FEM discretization in space. The class contains the necessary class members to add the necessary contributions to cell_matrix and cell_residual to the governing equations used to analyze lambda transport,
Usage Details:
For users:
In the input file, the evaporation and condensation rate constants need to be provided as follows:
* subsection Liquid Water Source Terms Equation
*   set Evaporation rate constant, [mol/(Pa-cm^2-s)] = 1.0e-7
*   set Condensation rate constant, [mol/(Pa-cm^2-s)] = 1.0e-8
* end
*
For developers:
* // Creating Equation object (in Application Header file)
* FuelCellShop::Equation::LiquidSourceEquation<dim> liquid_source_terms;
*
* // Declare parameters in application
* liquid_source_terms.declare_parameters(param);
*
* // Initialize in application
* liquid_source_terms.initialize(param);
*
* // Adjust the coupling terms and adding liquid source term into the equations
* std::vector<couplings_map> tmp;
* liquid_source_terms.adjust_internal_cell_couplings(tmp);
*
* // cell_matrix in application
* // Do a check against layer and it should match with the layers currently working for this equation class.
* // for eg: CCL is FuelCellShop::Layer::HomogeneousCL<dim> object.
* liquid_source_terms.assemble_cell_matrix(cell_matrices, cell_info, &CCL);
*
* // cell_residual in application
* liquid_source_terms.assemble_cell_residual(cell_vector, cell_info, &CCL);
*
Note
This class assembles the phase change source/sink term for the water vapour transport inside the layers. Also heat released/absorbed due to condensation/evaporation is also automatically assembled for the thermal transport equation.
Author
J. Zhou, Marc Secanell, 2015
Constructor & Destructor Documentation
template<int dim> FuelCellShop::Equation::LiquidSourceEquation< dim >::LiquidSourceEquation (FuelCell::SystemManagement & system_management, boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData > data = boost::shared_ptr< FuelCell::ApplicationCore::ApplicationData >())
Constructor.
template<int dim> virtual FuelCellShop::Equation::LiquidSourceEquation< dim >::~LiquidSourceEquation () virtual
Destructor.
Member Function Documentation
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::adjust_internal_cell_couplings (std::vector< couplings_map > &) const virtual
This function is used to adjust std::vector < internal_cell_couplings >, which is generated after getting internal_cell_couplings from all the equations being used in the application.
Note
It's very important to use this function, if we are considering source terms due to water sorption/desorption in the catalyst layers. It's also noteworthy that this function should be used after whole vector of internal_cell_couplings is created, and BEFORE make_cell_couplings of SystemManagement is called.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::assemble_cell_matrix (FuelCell::ApplicationCore::MatrixVector & cell_matrices, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo & cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer) virtual
Assemble local cell matrix.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::assemble_cell_residual (FuelCell::ApplicationCore::FEVector & cell_rhs, const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo & cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer) virtual
Assemble local cell residual.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::declare_parameters (ParameterHandler & param) const virtual
Declare parameters.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::get_kcond () const inline
Returns condensation rate constant, .
References FuelCellShop::Equation::LiquidSourceEquation< dim >::k_c.
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::get_kevap () const inline
Returns evaporation rate constant, .
References FuelCellShop::Equation::LiquidSourceEquation< dim >::k_e.
template<int dim> void FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters (double Temp, double c_pressure, double & psat, double & dpsat_dT, double & h_lv, double & dhlv_dT, double & Kelvin_factor, double & psat_kelvin, double & dpsat_kelvin_dpc, double & dpsat_kelvin_dT, FuelCellShop::Material::WaterVapor water) const inline protected
Inline function to reduce the repeatability of the code This function is used to compute Kelvin saturation pressure, latent heat of water and all the derivates with respect to Kelvin saturation pressure.
References Units::convert(), FuelCellShop::Material::LiquidWater::deriv_latentVap_heat(), FuelCellShop::Material::PureGas::get_Dwater_vapor_saturation_pressure_Dtemperature(), FuelCellShop::Material::PureGas::get_water_vapor_saturation_pressure(), FuelCellShop::Material::LiquidWater::latentVap_heat(), FuelCellShop::Equation::LiquidSourceEquation< dim >::M_water, Units::PER_C_UNIT3, Units::PER_UNIT2, Constants::R(), and FuelCellShop::Equation::LiquidSourceEquation< dim >::rho_l.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::initialize (ParameterHandler & param) virtual
Initialize parameters.
This class will call make_internal_cell_couplings and make_boundary_types.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::make_assemblers_cell_constant_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo & cell_info) protected virtual
This function computes Local CG FEM based assemblers - constant data (cell) and allocates the memory for shape functions, shape function gradients, and JxW_cell in Local CG FEM based assemblers - variable data (cell) .
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::make_assemblers_cell_variable_data (const typename FuelCell::ApplicationCore::DoFApplication< dim >::CellInfo & cell_info, FuelCellShop::Layer::BaseLayer< dim > *const layer) protected virtual
This function computes Local CG FEM based assemblers - variable data (cell) .
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::make_assemblers_generic_constant_data () protected virtual
This function computes Local CG FEM based assemblers - constant data (generic).
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::make_boundary_types () inline protected virtual
This function fills out boundary_types.
Currently, NOT IMPLEMENTED.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::make_output_types () inline protected virtual
This function fills out output_types.
Currently, NOT IMPLEMENTED.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> virtual void FuelCellShop::Equation::LiquidSourceEquation< dim >::print_equation_info () const virtual
The function prints out the equation's info about the internal coupling equations with the liquid water source terms.
Reimplemented from FuelCellShop::Equation::EquationBase< dim >.
template<int dim> void FuelCellShop::Equation::LiquidSourceEquation< dim >::set_relative_humility (double const x_wv) inline
Set the relative humility value from the operating condition class (using get_x_wv)
References FuelCellShop::Equation::LiquidSourceEquation< dim >::Relative_humility, and FuelCellShop::Equation::LiquidSourceEquation< dim >::Relative_humility_is_set.
Member Data Documentation
template<int dim> std::vector<double> FuelCellShop::Equation::LiquidSourceEquation< dim >::area_lv_cell protected
Interfacial surface area per unit volume, , at all quadrature points in the cell.
template<int dim> std::map<unsigned int, double> FuelCellShop::Equation::LiquidSourceEquation< dim >::capillary_pressure_current_flux_map protected
template<int dim> bool FuelCellShop::Equation::LiquidSourceEquation< dim >::cell_residual_counter protected
Counter set to TRUE when cell_residual is being assembled.
This ensures that only effective transport properties are calculated, not their derivatives. (improves speed)
template<int dim> std::vector<double> FuelCellShop::Equation::LiquidSourceEquation< dim >::darea_lv_dp_cell protected
, at all quadrature points in the cell.
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::fickswater_blockindex_pliquid protected
Block index for "liquid_capillary_pressure" corresponding to "Ficks Transport Equation - water".
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::fickswater_blockindex_trev protected
Block index for "temperature_of_REV" corresponding to "Ficks Transport Equation - water".
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::fickswater_blockindex_xwater protected
Block index for "water_molar_fraction" corresponding to "Ficks Transport Equation - water".
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::k_c protected
Condensation rate constant, .
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_kcond().
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::k_e protected
Evaporation rate constant, .
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_kevap().
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::last_iter_cell protected
Variable used to store the index in cell_info->global_data of the previous Newton solution The solution at the previous iteration is used to compute cell_matrix and cell_residual.
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::M_water protected
Molar weight of water in grams/mole.
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters().
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::p_cell protected
Total pressure in the cell.
template<int dim> VariableInfo FuelCellShop::Equation::LiquidSourceEquation< dim >::p_liquid_water protected
VariableInfo structure corresponding to "liquid_capillary_pressure".
template<int dim> std::vector< std::vector<double> > FuelCellShop::Equation::LiquidSourceEquation< dim >::phi_p_cell protected
shape functions.
phi_p_cell [ q ] [ k ] denotes -th shape function computed in -th quadrature point of the cell.
template<int dim> std::vector< std::vector<double> > FuelCellShop::Equation::LiquidSourceEquation< dim >::phi_T_cell protected
shape functions.
phi_T_cell [ q ] [ k ] denotes -th shape function computed in -th quadrature point of the cell.
template<int dim> std::vector< std::vector<double> > FuelCellShop::Equation::LiquidSourceEquation< dim >::phi_xwater_cell protected
shape functions.
phi_xwater_cell [ q ] [ k ] denotes -th shape function computed in -th quadrature point of the cell.
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::Relative_humility protected
This is used to return relative humility the when not solving water vapor as the solution variable.
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::set_relative_humility().
template<int dim> bool FuelCellShop::Equation::LiquidSourceEquation< dim >::Relative_humility_is_set protected
This is used to check if relative humility is set when not solving water vapor as the solution variable.
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::set_relative_humility().
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::rho_l protected
Density of liquid water, .
Referenced by FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters().
template<int dim> double FuelCellShop::Equation::LiquidSourceEquation< dim >::T_constant protected
This tempearture is used when not solving temperature as the solution variable.
template<int dim> VariableInfo FuelCellShop::Equation::LiquidSourceEquation< dim >::t_rev protected
VariableInfo structure corresponding to "temperature_of_REV".
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::thermal_blockindex_pliquid protected
Block index for "liquid_capillary_pressure" corresponding to "Thermal Transport Equation".
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::thermal_blockindex_trev protected
Block index for "temperature_of_REV" corresponding to "Thermal Transport Equation".
template<int dim> unsigned int FuelCellShop::Equation::LiquidSourceEquation< dim >::thermal_blockindex_xwater protected
Block index for "water_molar_fraction" corresponding to "Thermal Transport Equation".
template<int dim> VariableInfo FuelCellShop::Equation::LiquidSourceEquation< dim >::x_water protected
VariableInfo structure corresponding to "water_molar_fraction".
The documentation for this class was generated from the following file:
liquid_water_source_terms.h