OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Layer::GasDiffusionLayer< dim > Class Template Reference
FuelCellShop::Layer::GasDiffusionLayer< dim > Class Template Reference
Virtual class used to provide the interface for all GasDiffusionLayer children.
#include <gas_diffusion_layer.h>
Public Member Functions
Initalization
virtual void set_diffusion_species_name (std::string &name)
Member function used by some applications such as dummyGDL in order to know which value to return.
Accessors and info
const std::type_info & get_base_type () const
This member function returns a type_info object with the name of the base layer type the inherited class belongs to, i.e.
virtual void test_class () const
Class test.
Effective property calculators
virtual void effective_gas_diffusivity (const double &, const double &, double &) const
Compute the effective property in the pores of the GDL.
virtual void effective_gas_diffusivity (const double &, const double &, Tensor< 2, dim > &) const
Compute the effective property in the pores of the GDL.
virtual void effective_gas_diffusivity (std::vector< Tensor< 2, dim > > &) const
Return the effective diffusivity [m^2/s] for nonisothermal with/without two-phase case in the GDL.
virtual void derivative_effective_gas_diffusivity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const
Return the derivative of effective diffusivity w.r.t solution variables/design parameters for nonisothermal with/without two-phase case in the GDL.
virtual void effective_gas_diffusivity (Table< 2, double > &D_eff) const
Return the effective diffusivty in the GDL for all the gases assigned to the layer using set_gases_and_compute.
virtual void effective_gas_diffusivity (Table< 2, Tensor< 2, dim > > &D_eff) const
Return a tensor with the effective diffusivty in the GDL for all the gases assigned to the layer using set_gases_and_compute.
virtual void effective_electron_conductivity (double &) const
Compute the effective electron conductivity in the GDL.
virtual void effective_electron_conductivity (const double &, double &) const
Compute the effective electron conductivity in the GDL.
virtual void effective_electron_conductivity (Tensor< 2, dim > &) const
Compute the effective electron conductivity in the GDL.
virtual void effective_electron_conductivity (const double &, Tensor< 2, dim > &) const
Compute the effective electron conductivity in the GDL.
virtual void derivative_effective_electron_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
virtual void effective_thermal_conductivity (double &) const
Compute the effective thermal conductivity (isotropic) in the GDL.
virtual void effective_thermal_conductivity (Tensor< 2, dim > &) const
Compute the effective thermal conductivity (anisotropic) in the GDL.
virtual void effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the effective thermal conductivity (anisotropic) in the GDL, dependent on various solution variables, eg: Temperature.
virtual void derivative_effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective thermal conductivity in the GDL with respect to either the solution or design parameters.
virtual void gas_permeablity (double &) const
Compute the GDL gas permeability.
virtual void gas_permeablity (Tensor< 2, dim > &) const
Compute the GDL gas permeability.
virtual void derivative_gas_permeablity (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
virtual void liquid_permeablity (std::vector< Tensor< 2, dim > > &) const
Compute the anisotropic GDL liquid permeability , at all quadrature points in the cell.
virtual void derivative_liquid_permeablity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const
Compute the derivative of the anisotropic liquid permeability in the GDL with respect to either the solution or design parameters, at all quadrature points in the cell.
virtual void relative_liquid_permeability_PSD (std::vector< Tensor< 2, dim > > &) const
Compute the derivative of the anisotropic liquid permeability in the GDL with respect to either the solution or design parameters, at all quadrature points in the cell.
virtual void derivative_relative_liquid_permeablity_PSD (std::vector< double > &) const
virtual void derivative_relative_liquid_permeablity_PSD (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const
virtual void saturated_liquid_permeablity_PSD (double &) const
virtual void pcapillary (std::vector< double > &) const
Compute , at all quadrature points in the cell.
virtual void saturation_from_capillary_equation (std::vector< double > &) const
virtual void derivative_saturation_from_capillary_equation_PSD (std::vector< double > &) const
virtual void dpcapillary_dsat (std::vector< double > &) const
Compute , at all quadrature points in the GDL.
virtual void derivative_dpcapillary_dsat (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of in the GDL, with respect to either the solution or design parameters, at all quadrature points in the cell.
virtual void interfacial_surface_area (std::vector< double > &) const
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the GDL.
virtual void derivative_interfacial_surface_area (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the GDL.
virtual void interfacial_surface_area_PSD (std::vector< double > &) const
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the CL.
virtual void derivative_interfacial_surface_area_PSD (std::map< VariableNames, std::vector< double > > &) const
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the CL.
virtual void derivative_interfacial_surface_area_PSD (std::vector< double > &) const
Public Member Functions inherited from FuelCellShop::Layer::PorousLayer< dim >
void set_gases_and_compute (std::vector< FuelCellShop::Material::PureGas * > &gases_in, const double &pressure_in, const double &temperature_in)
Member function used to store all the gases that are in the pore space in the gas diffusion layer as well as their temperature [Kelvin] and total pressure [atm].
void compute_gas_diffusion (FuelCellShop::Material::PureGas *solute_gas, FuelCellShop::Material::PureGas *solvent_gas)
Member function used to compute bulk diffusion coefficients (and derivatives w.r.t temperature for non-isothermal case and store inside the layer).
void set_gases (std::vector< FuelCellShop::Material::PureGas * > &gases_in, const double &pressure_in)
Member function used to store all the gases that are in the pore space in the porous layer.
void set_gas_mixture (FuelCellShop::Material::GasMixture &rgas_mixture)
Set gas_mixture.
void set_porosity_permeability_tortuosity_booleans (const bool &rporosity_is_constant, const bool &rpermeability_is_constant, const bool &rtortuosity_is_constant)
Set.
void set_pressure (const SolutionVariable &p_in)
Member function used to set the temperature [Kelvin] at every quadrature point inside the cell.
void set_temperature (const SolutionVariable &T_in)
Member function used to set the temperature [Kelvin] at every quadrature point inside the cell.
void set_saturation (const SolutionVariable &s_in)
Member function used to set the liquid water saturation at every quadrature point inside the cell.
void set_capillary_pressure (const SolutionVariable &p_in)
Member function used to set the liquid water saturation at every quadrature point inside the cell.
FuelCellShop::Material::PureGas * get_gas_pointer (int index) const
Return the FuelCellShop::Material::PureGas pointer that is stored inside the class in the ith position.
std::vector
< FuelCellShop::Material::PureGas * > get_gases () const
Returns the vector of FuelCellShop::Material::PureGas pointers stored in the porous layer.
const
FuelCellShop::Material::GasMixture
*const get_gas_mixture () const
This function returns gas_mixture.
void get_gas_index (FuelCellShop::Material::PureGas *gas_type, int &index) const
Return the gas index in the GDL class.
void get_T_and_p (double &T, double &p) const
Return the constant temperature [Kelvin] and constant pressure [atm] inside the layer.
void get_p (double &p) const
Return the constant pressure [atm] inside the layer.
const bool & get_porosity_is_constant () const
This function returns porosity_is_constant.
const bool & get_permeability_is_constant () const
This function returns permeability_is_constant.
const bool & get_tortuosity_is_constant () const
This function returns tortuosity_is_constant.
double get_porosity () const
This function computes constant porosity in quadrature points of a mesh entity.
void get_porosity (std::vector< double > &dst) const
This function computes constant porosity in quadrature points of a mesh entity.
void get_porosity (std::vector< double > &dst, const std::vector< Point< dim > > &points) const
This function computes variable porosity in quadrature points of a mesh entity.
void get_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant permeability in quadrature points of a mesh entity.
void get_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable permeability in quadrature points of a mesh entity.
void get_SQRT_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes square root of constant permeability in quadrature points of a mesh entity.
void get_SQRT_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes square root of variable permeability in quadrature points of a mesh entity.
void get_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes inverse of constant permeability in quadrature points of a mesh entity.
void get_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes inverse of variable permeability in quadrature points of a mesh entity.
void get_SQRT_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes inverse of square root of constant permeability in quadrature points of a mesh entity.
void get_SQRT_permeability_INV (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes inverse of square root of variable permeability in quadrature points of a mesh entity.
void get_Forchheimer_permeability (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant Forchheimer permeability in quadrature points of a mesh entity.
void get_Forchheimer_permeability (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable Forchheimer permeability in quadrature points of a mesh entity.
void get_tortuosity (std::vector< SymmetricTensor< 2, dim > > &dst) const
This function computes constant tortuosity in quadrature points of a mesh entity.
void get_tortuosity (std::vector< SymmetricTensor< 2, dim > > &dst, const std::vector< Point< dim > > &points) const
This function computes variable tortuosity in quadrature points of a mesh entity.
virtual void gas_diffusion_coefficient (std::vector< double > &D_b) const
Member function used to compute diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
virtual void gas_diffusion_coefficient (std::vector< double > &D_b, std::vector< double > &dD_b_dT) const
Member function used to compute diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
void molecular_gas_diffusion_coefficient (std::vector< double > &D_m) const
Member function used to compute molecular diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
void molecular_gas_diffusion_coefficient (std::vector< double > &D_m, std::vector< double > &dD_m_dT) const
Member function used to compute molecular diffusion for a solute_gas, solvent_gas combination at a given temperature and pressure.
void Knudsen_diffusion (std::vector< double > &D) const
Member function used to get the Knudsen diffusivity in the layer after calling compute_gas_diffusion.
void Knudsen_diffusion (std::vector< double > &D, std::vector< double > &dD_dT) const
Member function used to compute the Knudsen diffusivity in the layer.after calling compute_gas_diffusion.
void compute_Knudsen_diffusion (const FuelCellShop::Material::PureGas *solute_gas, const SolutionVariable &T_in, std::vector< double > &D_k) const
Member function used to compute the Knudsen diffusivity in the layer.
void compute_Knudsen_diffusion (const FuelCellShop::Material::PureGas *solute_gas, const SolutionVariable &T_in, std::vector< double > &D_k, std::vector< double > &dD_k_dT) const
Member function used to compute the Knudsen diffusivity in the layer.
virtual void print_layer_properties () const
This member function is a virtual class that can be used to output to screen information from the layer.
Public Member Functions inherited from FuelCellShop::Layer::BaseLayer< dim >
virtual void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the variables for which you would like to compute the derivatives.
void set_position (const std::vector< Point< dim > > &p)
Member function used by some applications such as dummyGDL in order to know which value to return.
virtual void set_local_material_id (const unsigned int &id)
Function for setting local material id, for unit testing purposes.
void unset_local_material_id ()
Function for unsetting local material id, so that it isn't incorrectly used later Once the key is "unset" to some invalid value, an error will be thrown if the key is requested again without being set.
virtual void set_constant_solution (const double &value, const VariableNames &name)
Set those solution variables which are constant in the particular application.
virtual void set_solution (const std::vector< SolutionVariable > &)
If the effective properties in the layer depend on the solution, the solution for a given cell should be passed to the class using this member function.
bool belongs_to_material (const unsigned int material_id)
Check if a given cell belongs to the catalyst layer and assign.
const std::string & name_layer () const
Return the name of the layer.
virtual bool test_layer ()
This virtual class should be used for any derived class to be able to test the functionality of the class.
std::vector< unsigned int > get_material_ids ()
Return the local material id of the layer.
unsigned int local_material_id () const
Return the local material id of the layer, performs a check.
Static Public Member Functions
Instance Delivery (Public functions)
static void declare_GasDiffusionLayer_parameters (const std::string &gdl_section_name, ParameterHandler &param)
Function used to declare all the data necessary in the parameter files for all GasDiffusionLayer children.
static boost::shared_ptr
< FuelCellShop::Layer::GasDiffusionLayer
< dim > > create_GasDiffusionLayer (const std::string &gld_section_name, ParameterHandler &param)
Function used to select the appropriate GasDiffusionLayer type as specified in the ParameterHandler under line.
Static Public Attributes
Instance Delivery (Public variables)
static const std::string concrete_name
Concrete name used for objects of this class.
Protected Types
Instance Delivery (Types)
typedef std::map< std::string,
GasDiffusionLayer< dim > * > _mapFactory
This object is used to store all objects of type GasDiffusionLayer.
Protected Member Functions
Constructors, destructor, and initalization
GasDiffusionLayer ()
Replica Constructors.
~GasDiffusionLayer ()
Destructor.
GasDiffusionLayer (const std::string &name)
Constructor.
void declare_parameters (ParameterHandler &param) const
Declare parameters for a parameter file.
virtual void declare_parameters (const std::string &name, ParameterHandler &param) const
Declare parameters for a parameter file.
void initialize (ParameterHandler &param)
Member function used to read in data and initialize the necessary data to compute the coefficients.
Instance Delivery (Private functions)
virtual boost::shared_ptr
< FuelCellShop::Layer::GasDiffusionLayer
< dim > > create_replica (const std::string &name)
This member function is used to create an object of type gas diffusion layer.
Protected Member Functions inherited from FuelCellShop::Layer::PorousLayer< dim >
PorousLayer (const std::string &name)
Constructor.
PorousLayer ()
Constructor.
PorousLayer (const std::string &name, FuelCellShop::Material::GasMixture &gas_mixture)
Constructor.
virtual ~PorousLayer ()
Destructor.
void print_caller_name (const std::string &caller_name) const
This function is used to print out the name of another function that has been declared in the scope of this class, but not yet been implemented.
virtual void gas_diffusion_coefficients (Table< 2, double > &) const
Return the molecular diffusivty all the gases assigned to the layer using set_gases_and_compute.
virtual void derivative_gas_diffusion_coefficients (std::vector< Table< 2, double > > &) const
Return the derivative of the molecular diffusion coefficient with respect to the derivative flags for all the gases assigned to the layer using set_gases_and_compute.
Protected Member Functions inherited from FuelCellShop::Layer::BaseLayer< dim >
BaseLayer ()
Constructor.
BaseLayer (const std::string &name)
Constructor.
virtual ~BaseLayer ()
Destructor.
virtual void set_parameters (const std::string &object_name, const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Member function used to change the values in the parameter file for a given list of parameters.
virtual void set_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Set parameters in parameter file.
Static Protected Member Functions
Instance Delivery (Private and static)
static _mapFactory * get_mapFactory ()
Protected Attributes
Internal variables
std::string diffusion_species_name
If GDL properties are stored inside the class (e.g.
std::string PSD_type
PSD class type from input file.
double porosity
Porosity of the GDL.
Tensor< 2, dim > tortuosity_tensor
Tortuosity tensor of the GDL.
Tensor< 2, dim > thermal_conductivity_tensor
Tensor storing the effective thermal conductivity of the layer.
double electron_conductivity
Double storing the electric conductivity of the GDL is the layer is isotropic.
Tensor< 2, dim > electron_conductivity_tensor
Tensor storing the effective electronic conductivity of the layer.
Protected Attributes inherited from FuelCellShop::Layer::PorousLayer< dim >
FuelCellShop::Material::GasMixture * gas_mixture
Gas mixture.
std::vector
< FuelCellShop::Material::PureGas * > gases
Gases inside a porous layer.
bool porosity_is_constant
Variable defining if the porosity is constant.
bool permeability_is_constant
Variable defining if the permeability is constant.
bool tortuosity_is_constant
Variable defining if the tortuosity is constant.
double porosity
User defined constant porosity.
bool use_Bosanquet
Boolean flag that specifies if Knudsen effects should be accounted for.
double Knudsen_radius
Parameter used to define Knudsen pore radius.
SymmetricTensor< 2, dim > permeability
User defined constant permeability, m^2.
SymmetricTensor< 2, dim > SQRT_permeability
Square root of user defined constant permeability, m.
SymmetricTensor< 2, dim > permeability_INV
Inverse of user defined constant permeability, 1/m^2.
SymmetricTensor< 2, dim > SQRT_permeability_INV
Inverse of square root of user defined constant permeability, 1/m.
SymmetricTensor< 2, dim > Forchheimer_permeability
User defined constant Forchheimer permeability, 1/m.
SymmetricTensor< 2, dim > tortuosity
User defined constant tortuosity.
std::string diffusion_species_name
If GDL properties are stored inside the class (e.g DummyGDL) then, return the property stored under coefficient_name name.
double temperature
Temperature [K] used to compute gas diffusivity.
double pressure
Total pressure [atm] used to compute gas diffusivity.
SolutionVariable p_vector
Pressure at every quadrature point inside the cell in [Pa].
SolutionVariable T_vector
Temperature at every quadrature point inside the cell in [K].
SolutionVariable s_vector
Liquid water saturation at every quadrature point inside the cell [-].
SolutionVariable capillary_pressure_vector
Liquid water capillary pressure at every quadrature point inside the cell in [Pa].
Table< 2, double > D_ECtheory
Tensor of diffusion coefficients This are computed with setting up the gas so that they do not need to be recomputed all the time.
std::vector< Table< 2, double > > dD_ECtheory_dx
Vector of tensors for the derivative of the diffusion coefficients – This are computed with setting up the gas so that they do not need to be recomputed all the time.
std::vector< double > D_molecular
Vector of molecular diffusion coefficients at every quadrature point inside the cell in m^2/s.
std::vector< double > dD_molecular_dT
Vector of derivatives for molecular diffusion coefficients w.r.t temperature, at every quadrature in m^2/s.
std::vector< double > D_k
Vector of Knudsen diffusion coefficients at every quadrature point inside the cell in m^2/s.
std::vector< double > dD_k_dT
Vector of derivatives for Knudsen diffusion coefficients w.r.t temperature, at every quadrature in m^2/s.
std::vector< double > D_bulk
Vector of bulk diffusion coefficients at every quadrature point inside the cell.
std::vector< double > dD_bulk_dT
Vector of derivative of bulk diffusion coefficients w.r.t temperature, at every quadrature point inside the cell.
bool PSD_is_used
Boolean flag to specify if a PSD is to be used to estimate saturation, permeability, etc.
std::string PSD_type
PSD class type from input file.
boost::shared_ptr
< FuelCellShop::MicroScale::BasePSD
< dim > > PSD
Pointer to the PSD object.
FuelCellShop::MicroScale::BasePSD
< dim > * psd_pointer
Pointer to the PSD object.
FuelCellShop::Material::PureGas * solute_gas
Pointer used to store the solute gas for computing binary diffusion coefficients.
FuelCellShop::Material::PureGas * solvent_gas
Pointer used to store the solute gas for computing binary diffusion coefficients.
Protected Attributes inherited from FuelCellShop::Layer::BaseLayer< dim >
const std::string name
Name of the layer.
std::vector< unsigned int > material_ids
List of material IDs that belong to the layer.
std::vector< Point< dim > > point
Coordinates of the point where we would like to compute the effective properties.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives.
std::map< VariableNames, double > constant_solutions
Map storing values of solution variables constant in a particular application.
Detailed Description
template<int dim>
class FuelCellShop::Layer::GasDiffusionLayer< dim >
Virtual class used to provide the interface for all GasDiffusionLayer children.
No object of type GasDiffusionLayer should ever be created, instead this layer is used to initialize pointers of type GasDiffusionLayer. The class has a database of children such that it will declare all necessary parameters for all children in the input file, read the input file, create the appripriate children and return a pointer to GasDiffusionLayer with the children selected.
All public functions are virtual but the static functions used to declare parameters and to initialize a pointer of GasDiffusionLayer, i.e. declare_all_GasDiffusionLayer_parameters, set_all_GasDiffusionLayer_parameters and create_GasDiffusionLayer.
Usage Details:
In order to create a gas diffusion layer within an application, the following steps need to be taken.
First, in the application .h file, create a pointer to a GasDiffusionLayer object, i.e.
* boost::shared_ptr<FuelCellShop::Layer::GasDiffusionLayer<dim> > CGDL;
*
This pointer object will be available anywhere inside the application. Because we do not want to worry about deleting the pointer afterwards, we use a Boost pointer which has its own memory management algorithms. See the Boost website for more information
Once the pointer is available, we need to do three things in the application
Call declare_all_GasDiffusionLayer_parameters in the application declare_parameters() member function. This member function is used to define all parameters that can be read from the input file
Call create_GasDiffusionLayer and initialize. The former member function will fill the pointer created above with the appropriate gas diffusion layer you have selected in the input file. Then, initialize reads from the input file all the data from the file in order to setup the object.
The object is ready for use now.
Here is a code example from app_cathode.cc:
* //--------- IN DECLARE_PARAMETERS ------------------------------------------------------
* template <int dim>
* void
* NAME::AppCathode<dim>::declare_parameters(ParameterHandler& param)
* {
*   (...)
*   // Declare section on the input file where all info will be stored. In this case Fuel Cell Data > Cathode gas diffusion layer
*   FuelCellShop::Layer::GasDiffusionLayer<dim>::declare_GasDiffusionLayer_parameters("Cathode gas diffusion layer", param);
*   (...)
* }
*
* //--------- IN INITIALIZE ------------------------------------------------------
* template <int dim>
* void
* NAME::AppCathode<dim>::_initialize(ParameterHandler& param)
* {
*  (...)
*   // Initialize layer classes:
*   std::vector< FuelCellShop::Material::PureGas * > gases;
*   gases.push_back(&oxygen);
*   gases.push_back(&nitrogen);
*
*   CGDL = FuelCellShop::Layer::GasDiffusionLayer<dim>::create_GasDiffusionLayer("Cathode gas diffusion layer",param);
*   // Here, I specify the gases that exist in the GDL and their temperature and pressure (based on operating conditions):
*   CGDL->set_gases_and_compute(gases, OC.get_pc_atm (), OC.get_T());
*   (...)
* }
*
Author
M. Secanell, 2013
Member Typedef Documentation
template<int dim> typedef std::map< std::string, GasDiffusionLayer<dim>* > FuelCellShop::Layer::GasDiffusionLayer< dim >::_mapFactory protected
This object is used to store all objects of type GasDiffusionLayer.
Constructor & Destructor Documentation
template<int dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::GasDiffusionLayer () protected
Replica Constructors.
Warning
For internal use only.
Constructor used only to create a prototype. Do not use in general since this will not include the name of the section in the parameter file you need.
template<int dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::~GasDiffusionLayer () protected
Destructor.
template<int dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::GasDiffusionLayer (const std::string & name) protected
Constructor.
Member Function Documentation
template<int dim> static boost::shared_ptr<FuelCellShop::Layer::GasDiffusionLayer<dim> > FuelCellShop::Layer::GasDiffusionLayer< dim >::create_GasDiffusionLayer (const std::string & gld_section_name, ParameterHandler & param) inline static
Function used to select the appropriate GasDiffusionLayer type as specified in the ParameterHandler under line.
* set Gas diffusion layer type = DummyGDL
*
current options are [ DesignFibrousGDL | DummyGDL | SGL24BA ]
The class will read the appropriate section in the parameter file, i.e. the one with name
Parameters
gld_section_name,create an object of the desired type and return it.
References FuelCellShop::Layer::GasDiffusionLayer< dim >::create_replica(), FuelCellShop::Layer::GasDiffusionLayer< dim >::get_mapFactory(), and FcstUtilities::log.
template<int dim> virtual boost::shared_ptr<FuelCellShop::Layer::GasDiffusionLayer<dim> > FuelCellShop::Layer::GasDiffusionLayer< dim >::create_replica (const std::string & name) inline protected virtual
This member function is used to create an object of type gas diffusion layer.
Warning
This class MUST be redeclared in every child.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >, FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::SGL24BA< dim >.
References FcstUtilities::log.
Referenced by FuelCellShop::Layer::GasDiffusionLayer< dim >::create_GasDiffusionLayer().
template<int dim> static void FuelCellShop::Layer::GasDiffusionLayer< dim >::declare_GasDiffusionLayer_parameters (const std::string & gdl_section_name, ParameterHandler & param) inline static
Function used to declare all the data necessary in the parameter files for all GasDiffusionLayer children.
This member function should be used instead of declare_parameters() when we want to use a GasDiffusionLayer pointer that selects the type of GDL to run at runtime.
Parameters
gld_section_name Name of the section that will encapuslate all the information about the GDL
param ParameterHandler object used to store all information about the simulation. Used to read the parameter file.
The parameter file would look as follows:
* subsection Fuel cell data
* (...)
* subsection Cathode gas diffusion layer           #This is the name provided in gld_section_name
*
*   set Gas diffusion layer type = DummyGDL #[ DesignFibrousGDL | DummyGDL | SGL24BA ]
*   set Material id = 2
*
*     subsection DummyGDL         # This is the subsection for the first children
*       set Oxygen diffusion coefficient, [cm^2/s] = 0.22
*       set Electrical conductivity, [S/cm] = 40
*     end
*
*     subsection DesignFibrousGDL
*       set Porosity = 0.6
*       ## Anisotropy
*       set Anisotropic transport = true                    # (default) false
*       set Method effective transport properties in pores = Tomadakis  # (default) Bruggemann | Given | Percolation | Tomadakis | Mezedur
*       set Method effective transport properties in solid = Percolation    # (default) Bruggemann | Given | Percolation
*       (...)
*     end
* end
* (...)
* end
*
References FuelCellShop::Layer::GasDiffusionLayer< dim >::get_mapFactory().
template<int dim> void FuelCellShop::Layer::GasDiffusionLayer< dim >::declare_parameters (ParameterHandler & param) const inline protected virtual
Declare parameters for a parameter file.
Deprecated:
Use declare_all_GasDiffusionLayer_parameters
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::SGL24BA< dim >.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::declare_parameters (const std::string & name, ParameterHandler & param) const protected virtual
Declare parameters for a parameter file.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >, FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::SGL24BA< dim >.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_dpcapillary_dsat (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of in the GDL, with respect to either the solution or design parameters, at all quadrature points in the cell.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_effective_electron_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective electron conductivity in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_effective_gas_diffusivity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const inline virtual
Return the derivative of effective diffusivity w.r.t solution variables/design parameters for nonisothermal with/without two-phase case in the GDL.
It transforms bulk diffusion properties computed using compute_gas_diffusion method and transforms it into an effective property, taking into account the porosity, saturation and GDL structure (Anisotropic case), at all quadrature points of the cell.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective thermal conductivity in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_gas_permeablity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the effective gas permeability in the GDL with respect to either the solution or design parameters.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_interfacial_surface_area (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the GDL.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags().
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_interfacial_surface_area_PSD (std::map< VariableNames, std::vector< double > > &) const inline virtual
Compute the derivative of the liquid-gas interfacial surface area per unit volume, with respect to either the solution variables or design parameters, at all quadrature points in the CL.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags().
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_interfacial_surface_area_PSD (std::vector< double > &) const inline virtual
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_liquid_permeablity (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const inline virtual
Compute the derivative of the anisotropic liquid permeability in the GDL with respect to either the solution or design parameters, at all quadrature points in the cell.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_relative_liquid_permeablity_PSD (std::vector< double > &) const inline virtual
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_relative_liquid_permeablity_PSD (std::map< VariableNames, std::vector< Tensor< 2, dim > > > &) const inline virtual
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::derivative_saturation_from_capillary_equation_PSD (std::vector< double > &) const inline virtual
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::dpcapillary_dsat (std::vector< double > &) const inline virtual
Compute , at all quadrature points in the GDL.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_electron_conductivity (double &) const inline virtual
Compute the effective electron conductivity in the GDL.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_electron_conductivity (const double & , double &) const inline virtual
Compute the effective electron conductivity in the GDL.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_electron_conductivity (Tensor< 2, dim > &) const inline virtual
Compute the effective electron conductivity in the GDL.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, FuelCellShop::Layer::DesignFibrousGDL< dim >, and FuelCellShop::Layer::SGL24BA< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_electron_conductivity (const double & , Tensor< 2, dim > &) const inline virtual
Compute the effective electron conductivity in the GDL.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_gas_diffusivity (const double & , const double & , double &) const inline virtual
Compute the effective property in the pores of the GDL.
This is used for example to compute effective diffusivity of gases. The method takes in bulk diffusion coefficient [m^2/s] and liquid water saturation as the first and second argument respectively. This routine is used in the isotropic case.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_gas_diffusivity (const double & , const double & , Tensor< 2, dim > &) const inline virtual
Compute the effective property in the pores of the GDL.
This is used for example to compute effective diffusivity of gases. The method takes in bulk diffusion coefficient [m^2/s] and liquid water saturation as the first and second argument respectively. This routine can be used either in the isotropic or anisotripic case
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_gas_diffusivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Return the effective diffusivity [m^2/s] for nonisothermal with/without two-phase case in the GDL.
It takes bulk diffusivity, computed using compute_gas_diffusion method and transforms it into an effective property, taking into account the porosity, saturation and GDL structure (Anisotropic case), at all quadrature points of the cell.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_gas_diffusivity (Table< 2, double > & D_eff) const inline virtual
Return the effective diffusivty in the GDL for all the gases assigned to the layer using set_gases_and_compute.
This routine uses FuelCellShop::Mixture::ChapmanEnskog to compute the binary diffusivity for each gas with respect to each other. If the layer contains three gases the vector returns D12, D13, D23. For 4 gases, it returns D12, D13, D14, D23, D24, D34.
Deprecated:
Use compute_gas_diffusion with appropriate gases and then effective_gas_diffusivity
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_gas_diffusivity (Table< 2, Tensor< 2, dim > > & D_eff) const inline virtual
Return a tensor with the effective diffusivty in the GDL for all the gases assigned to the layer using set_gases_and_compute.
This routine uses FuelCellShop::Mixture::ChapmanEnskog to compute the binary diffusivity for each gas with respect to each other. If the layer contains three gases the vector returns D12, D13, D23. For 4 gases, it returns D12, D13, D14, D23, D24, D34 (Anisotropic case).
Deprecated:
Use compute_gas_diffusion with appropriate gases and then effective_gas_diffusivity
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, FuelCellShop::Layer::SGL24BA< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_thermal_conductivity (double &) const inline virtual
Compute the effective thermal conductivity (isotropic) in the GDL.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_thermal_conductivity (Tensor< 2, dim > &) const inline virtual
Compute the effective thermal conductivity (anisotropic) in the GDL.
Reimplemented in FuelCellShop::Layer::SGL24BA< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::effective_thermal_conductivity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the effective thermal conductivity (anisotropic) in the GDL, dependent on various solution variables, eg: Temperature.
Reimplemented in FuelCellShop::Layer::DummyGDL< dim >, and FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::gas_permeablity (double &) const inline virtual
Compute the GDL gas permeability.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::gas_permeablity (Tensor< 2, dim > &) const inline virtual
Compute the GDL gas permeability.
References FcstUtilities::log.
template<int dim> const std::type_info& FuelCellShop::Layer::GasDiffusionLayer< dim >::get_base_type () const inline virtual
This member function returns a type_info object with the name of the base layer type the inherited class belongs to, i.e.
GasDiffusionLayer
MicroPorousLayer
CatalystLayer
MembraneLayer
SolidLayer
Channel
Note that this is necessary if we want to find out not the name of the actual class which can be obtain using
const std::type_info& name = typeid(*this)
but the name of the parent class.
Note
Do not re-implement this class in children classes
Reimplemented from FuelCellShop::Layer::BaseLayer< dim >.
template<int dim> static _mapFactory* FuelCellShop::Layer::GasDiffusionLayer< dim >::get_mapFactory () inline static protected
Referenced by FuelCellShop::Layer::GasDiffusionLayer< dim >::create_GasDiffusionLayer(), and FuelCellShop::Layer::GasDiffusionLayer< dim >::declare_GasDiffusionLayer_parameters().
template<int dim> void FuelCellShop::Layer::GasDiffusionLayer< dim >::initialize (ParameterHandler & param) protected virtual
Member function used to read in data and initialize the necessary data to compute the coefficients.
Note
This routine is called in create_GasDiffusionLayer.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::SGL24BA< dim >.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::interfacial_surface_area (std::vector< double > &) const inline virtual
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the GDL.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::interfacial_surface_area_PSD (std::vector< double > &) const inline virtual
Compute the liquid-gas interfacial surface area per unit volume, , at all quadrature points in the CL.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::liquid_permeablity (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the anisotropic GDL liquid permeability , at all quadrature points in the cell.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::pcapillary (std::vector< double > &) const inline virtual
Compute , at all quadrature points in the cell.
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::relative_liquid_permeability_PSD (std::vector< Tensor< 2, dim > > &) const inline virtual
Compute the derivative of the anisotropic liquid permeability in the GDL with respect to either the solution or design parameters, at all quadrature points in the cell.
The parameters with respect to which the derivatives are computed are setup in FuelCellShop::Layer::set_derivative_flags()
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::saturated_liquid_permeablity_PSD (double &) const inline virtual
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::saturation_from_capillary_equation (std::vector< double > &) const inline virtual
Reimplemented from FuelCellShop::Layer::PorousLayer< dim >.
Reimplemented in FuelCellShop::Layer::DesignFibrousGDL< dim >.
References FcstUtilities::log.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::set_diffusion_species_name (std::string & name) inline virtual
Member function used by some applications such as dummyGDL in order to know which value to return.
For other classes this class is not used.
Deprecated:
This member function should not be used.
template<int dim> virtual void FuelCellShop::Layer::GasDiffusionLayer< dim >::test_class () const virtual
Class test.
Member Data Documentation
template<int dim> const std::string FuelCellShop::Layer::GasDiffusionLayer< dim >::concrete_name static
Concrete name used for objects of this class.
This name is used when setting up the subsection where the data is stored in the input file.
The data will be store under
* subsection name_specified_in_constructor
*    set Material id = 2
*    set Gas diffusion layer type = DummyGDL # <-here I select the type of object of type GasDiffusionLayer
*    subsection DummyGDL # <- this is the concrete_name for this class
*       set all info relevant to this object
*    end
* end
*
template<int dim> std::string FuelCellShop::Layer::GasDiffusionLayer< dim >::diffusion_species_name protected
If GDL properties are stored inside the class (e.g.
DummyGDL) then, return the property stored under coefficient_name name
template<int dim> double FuelCellShop::Layer::GasDiffusionLayer< dim >::electron_conductivity protected
Double storing the electric conductivity of the GDL is the layer is isotropic.
Otherwise the value is set to zero.
template<int dim> Tensor<2, dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::electron_conductivity_tensor protected
Tensor storing the effective electronic conductivity of the layer.
This function if used if the layer is anisotropic.
template<int dim> double FuelCellShop::Layer::GasDiffusionLayer< dim >::porosity protected
Porosity of the GDL.
template<int dim> std::string FuelCellShop::Layer::GasDiffusionLayer< dim >::PSD_type protected
PSD class type from input file.
template<int dim> Tensor<2, dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::thermal_conductivity_tensor protected
Tensor storing the effective thermal conductivity of the layer.
template<int dim> Tensor<2,dim> FuelCellShop::Layer::GasDiffusionLayer< dim >::tortuosity_tensor protected
Tortuosity tensor of the GDL.
The documentation for this class was generated from the following file:
gas_diffusion_layer.h