OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Geometry::GridBase< dim > Class Template Reference
FuelCellShop::Geometry::GridBase< dim > Class Template Reference
FuelCell Geometry information class.
#include <geometry.h>
Public Member Functions
virtual void generate_grid (Triangulation< dim > &)
Function is empty and must be reimplemented in derived classes.
void generate_grid_with_curved_boundaries (Triangulation< dim > &triangulation, const types::boundary_id &bdry_id, boost::shared_ptr< Boundary< dim > > boundary) const
This function is like the previous one generate_grid() but allows to assign a curved boundary boundary to that with the boundary id bdry_id.
std::vector< unsigned int > get_material_id (const std::string) const
Return a vector with all material ids associated with string.
unsigned int get_boundary_id (ParameterHandler &param, const std::string boundary) const
Return boundary id.
unsigned int get_boundary_id (const std::string) const
Return boundary id.
void output_grid (const Triangulation< dim > &triangulation, const std::string filename) const
Output the grid.
void refine_area (Triangulation< dim > &triangulation, const unsigned int material_id)
Refine a certain part of the grid depending on material_ID given.
std::string get_mesh_type ()
Return the type of mesh that is being used.
Geometric data
double L_channel_c ()
Return the Width of the cathode gas channel.
double L_channelLength_c ()
Return the Length of the cathode gas channel.
double L_channelHeight_c ()
Return the Height of the cathode gas channel.
double L_channelEntrance_c ()
Return the Entrance Length of the cathode gas channel.
double L_channelExit_c ()
Return the Exit Length of the cathode gas channel.
double L_land_c ()
Return the Width of the cathode current collector.
double L_gdl_c ()
Return the Thickness of the cathode gas diffusion layer.
std::vector< double > L_cat_c ()
Return the thickness of the cathode catalyst layer.
double L_mpl_c ()
Return the Thickness of the cathode microporous layer.
double L_mem ()
Return the Thickness of the membrane.
double L_cat_a ()
Return the Thickness of the anode catalyst layer.
double L_mpl_a ()
Return the Thickness of the anode microporous layer.
double L_gdl_a ()
Return the Thickness of the anode gas diffusion layer.
double L_channel_a ()
Return the Width of the anode gas channel.
double L_land_a ()
Return the Width of the anode current collector.
Static Public Member Functions
Instance Delivery (Public functions)
static void declare_GridGenerator_parameters (ParameterHandler &param)
Function used to declare all the data necessary in the parameter files for all GridBase children.
static boost::shared_ptr
< FuelCellShop::Geometry::GridBase
< dim > > create_GridGenerator (ParameterHandler &param)
Generate the appropriate mesh generator object based on the parameters in the input file.
Public Attributes
bool read_from_file
boost::shared_ptr< GridIn< dim > > grid_in
GridIn class object of dealii which allows to read various types of mesh formats.
Protected Types
Instance Delivery (Types)
typedef std::map< std::string,
GridBase< dim > * > _mapFactory
This object is used to store all objects of type GasDiffusionLayer.
Protected Member Functions
Constructors, destructor, and initalization
GridBase ()
Constructor.
virtual ~GridBase ()
Destructor.
void initialize (ParameterHandler &param)
Instance Delivery (Private functions)
virtual boost::shared_ptr
< FuelCellShop::Geometry::GridBase
< dim > > create_replica (const std::string &name)
This member function is used to create an object of type gas diffusion layer.
Internal functions
void print_material_id_and_boundary_id (const Triangulation< dim > &triangulation) const
Static Protected Member Functions
Instance Delivery (Private and static)
static _mapFactory * get_mapFactory ()
Protected Attributes
std::string mesh_type_name
Specify if you would like to load a mesh from file or if you would like a module from the mesh generator Options: File | Cathode | Anode | CathodeMPL | Pemfc | PemfcMPL.
std::string mesh_name
Name of the mesh file.
std::string mesh_type
Specify if it is a UNV file, MSH file, etc.
unsigned int num_refine
Initial number of refinements.
PEMFC Data (Dimensions)
double l_channel_c
Width of the cathode gas channel.
double l_channelLength_c
Length of the cathode gas channel.
double l_channelHeight_c
Height of the cathode gas channel.
double l_channelEntrance_c
Entrance length of the cathode gas channel.
double l_channelExit_c
Exit Length of the cathode gas channel.
double l_land_c
Width of the cathode current collector.
double l_gdl_c
Thickness of the cathode gas diffusion layer.
double l_mpl_c
Thickness of the cathode microporous layer.
std::vector< double > l_cat_c
Thickness of the cathode catalyst layer.
double l_mem
Thickness of the membrane.
double l_cat_a
Thickness of the anode catalyst layer.
double l_mpl_a
Thickness of the anode microporous layer.
double l_gdl_a
Thickness of the anode gas diffusion layer.
double l_channel_a
Width of the anode gas channel.
double l_land_a
Width of the anode current collector.
double l_cube
Cube edge for HyperCube mesh.
Internal Mesh Generator Data
unsigned int num_vert
Number of cells tall the initial grid.
unsigned int num_c_Channel
Number of cells wide cathode channel.
unsigned int num_c_GDL
Number of cells wide cathode gas diffusion layer.
unsigned int num_c_MPL
Number of cells wide cathode microporous layer.
unsigned int num_c_CL
Number of cells wide cathode catalyst layer.
unsigned int num_membrane
Number of cells wide membrane layer.
unsigned int num_a_CL
Number of cells wide anode catalyst layer.
unsigned int num_a_MPL
Number of cells wide anode microporous layer.
unsigned int num_a_GDL
Number of cells wide anode gas diffusion layer.
Material ID Data
unsigned int test_mid
Material id for test cell (GridTest app)
unsigned int c_CC_mid
Material id cathode current collector.
unsigned int c_GC_mid
Material id cathode gas channel.
unsigned int c_GDL_mid
Material id cathode GDL.
unsigned int c_MPL_mid
Material id cathode MPL.
std::vector< unsigned int > c_CL_mid
Material id cathode catalyst layer.
unsigned int membrane_mid
Material id membrane.
unsigned int a_CL_mid
Material id anode catalyst layer.
unsigned int a_MPL_mid
Material id anode MPL.
unsigned int a_GDL_mid
Material id anode GDL.
unsigned int a_CC_mid
Material id anode current collector.
unsigned int a_GC_mid
Material id anode gas channel.
Boundary ID Data
unsigned int c_Ch_Inlet_bid
Boundary id cathode channel inlet.
unsigned int c_Ch_Outlet_bid
Boundary id cathode channel outlet.
unsigned int c_Ch_base_bid
Boundary id cathode channel entrance/exit base.
unsigned int c_Ch_roof_bid
Boundary id cathode channel entrance/exit roof.
unsigned int c_Ch_GDL_bid
Boundary id cathode channel and GDL.
unsigned int c_BPP_GDL_bid
Boundary id cathode BPP and GDL.
unsigned int c_GDL_CL_bid
Boundary id cathode GDL and CL.
unsigned int c_CL_Membrane_bid
Boundary id cathode CL and membrane.
unsigned int c_GDL_MPL_bid
Boundary id cathode GDL and MPL.
unsigned int c_MPL_CL_bid
Boundary id cathode MPL and CL.
unsigned int a_Membrane_CL_bid
Boundary id anode membrane and CL.
unsigned int a_CL_GDL_bid
Boundary id anode CL and GDL.
unsigned int a_GDL_BPP_bid
Boundary id anode GDL and BPP.
unsigned int a_GDL_Ch_bid
Boundary id anode GDL and channel.
unsigned int a_MPL_GDL_bid
Boundary id anode GDL and MPL.
unsigned int a_CL_MPL_bid
Boundary id anode MPL and CL.
unsigned int a_Ch_Inlet_bid
Boundary id cathode channel inlet.
unsigned int a_Ch_Outlet_bid
Boundary id cathode channel outlet.
unsigned int a_Ch_base_bid
Boundary id cathode channel entrance/exit base.
unsigned int a_Ch_roof_bid
Boundary id cathode channel entrance/exit roof.
Agglomerate Data
double r_agg
Agglomerate radius.
double delta_agg
Electrolyte thin film thickness.
unsigned int r_agg_mid
Porous Agglomerate Material ID.
unsigned int delta_agg_mid
Electrolyte Thin Film Material ID.
unsigned int r_delta_bid
Boundary ID for agglomerate/thin film boundary.
unsigned int delta_bid
Boundary ID for thin film external boundary.
Point< dim > center
Centre point of the circular/spherical domain.
Detailed Description
template<int dim>
class FuelCellShop::Geometry::GridBase< dim >
FuelCell Geometry information class.
Class used to store the geometry and grid information for an application
Derived classes should contain the specific implementation of mesh generation and manipulation of the triangulation object.
Note
Concerning boundary id's: All internal boundary id's must be set to 255 for deal.ii. When implementing continuty over the domain, this is the default parameter value deal.ii checks. See the deal.ii documentation for more information.
Usage Details:
GridBase is a virtual class that contains a map to all children applications. Using the map, GridBase can pass the user a pointer to the desired class as specified in the input file.
All children use the parameters in declare_GridGenerator_parameters; however, they have a re-implementation of the function generate_grid and other functions.
To use the class, first create a pointer to the base object using:
  boost::shared_ptr< FuelCellShop::Geometry::GridBase<dim> > grid;
*
Then, declare the data in the input file using:
  FuelCellShop::Geometry::GridBase<dim>::declare_GridGenerator_parameters(param);
*
Finally, read the ParameterHandler object to initalize the grid. Then, use the objec to generate the desired grid:
  grid = FuelCellShop::Geometry::GridBase<dim>::create_GridGenerator (param);
  grid->generate_grid(*this->tr);
*
Author
M. Secanell, 2009-13
L. Brikett, 2009
P. Dobson, 2009-11
Member Typedef Documentation
template<int dim> typedef std::map< std::string, GridBase<dim>* > FuelCellShop::Geometry::GridBase< dim >::_mapFactory protected
This object is used to store all objects of type GasDiffusionLayer.
Constructor & Destructor Documentation
template<int dim> FuelCellShop::Geometry::GridBase< dim >::GridBase () protected
Constructor.
template<int dim> virtual FuelCellShop::Geometry::GridBase< dim >::~GridBase () protected virtual
Destructor.
Member Function Documentation
template<int dim> static boost::shared_ptr<FuelCellShop::Geometry::GridBase<dim> > FuelCellShop::Geometry::GridBase< dim >::create_GridGenerator (ParameterHandler & param) inline static
Generate the appropriate mesh generator object based on the parameters in the input file.
References FuelCellShop::Geometry::GridBase< dim >::create_replica(), FuelCellShop::Geometry::GridBase< dim >::get_mapFactory(), and FcstUtilities::log.
template<int dim> virtual boost::shared_ptr<FuelCellShop::Geometry::GridBase<dim> > FuelCellShop::Geometry::GridBase< dim >::create_replica (const std::string & name) inline protected virtual
This member function is used to create an object of type gas diffusion layer.
Warning
This class MUST be redeclared in every child.
Reimplemented in FuelCellShop::Geometry::GridTest< dim >, FuelCellShop::Geometry::Agglomerate< dim >, FuelCellShop::Geometry::PemfcMPL< dim >, FuelCellShop::Geometry::CathodeMPL< dim >, FuelCellShop::Geometry::HyperCube< dim >, and FuelCellShop::Geometry::GridExternal< dim >.
References FcstUtilities::log.
Referenced by FuelCellShop::Geometry::GridBase< dim >::create_GridGenerator().
template<int dim> static void FuelCellShop::Geometry::GridBase< dim >::declare_GridGenerator_parameters (ParameterHandler & param) static
Function used to declare all the data necessary in the parameter files for all GridBase children.
*  section Grid generation
*    +++++++ OPTIONS FROM APPFRAME +++++++++++
*    set Sort by component = true
*    set Sort Cuthill-McKee = false
*    set Initial refinement = 1  # Number of times we want to globally refine the original grid before starting to solve
*    set Refinement = global   # OPTIONS: global|adaptive|single|steps|circle
*    set Refinement threshold = 0.3
*    set Coarsening threshold = 0
*    set Distort = 0
*    +++++++ END OPTIONS FROM APPFRAME +++++++++++
*    set Type of mesh = Cathode # OPTIONS: GridExternal | Cathode | Anode | CathodeMPL | Pemfc | PemfcMPL | Agglomerate -- Type of mesh that you would like to generate.")
*    set File name = test.unv   # Name of the mesh file
*    set File type = UNV        # Meshtype (see deal.ii supported mesh types
*    ==== Section related to internal mesh generator: =======
*    subsection Internal mesh generator parameters
*      subsection Dimensions
*       set Cathode current collector width [cm] = 0.1 # Thickness of the rib of the bipolar plates (BPP)
*       set Cathode channel width [cm] = 0.1           # Thickness of the channel on the BPP
*       set Cathode CL thickness [cm] = 1E-3           # Thickness of the cathode catalyst layer [cm]
*       set Cathode GDL thickness [cm]  = 2E-2         # Thickness of the cathode gas diffusion layer [cm]
*       set Cathode MPL thickness [cm] = 2E-3          # Thickness of the cathode microporous layer [cm]
*       set Membrane thickness [cm] = 2E-2             # Thickness of the membrane [cm]
*       set Anode MPL thickness [cm] = 2E-3            # Thickness of the anode microporous layer [cm]
*       set Anode CL thickness [cm] = 1E-3             # Thickness of the anode catalyst layer [cm]
*       set Anode GDL thickness [cm] = 2E-2            # Thickness of the anode gas diffusion layer [cm]
*       set Anode current collector width [cm] = 0.1   # Thickness of the rib of the bipolar plates (BPP) [cm]
*       set Anode channel width [cm] = 0.1             # Thickness of the channel on the BPP
*       set Agglomerate radius [cm] = 100e-7           # Aggomerate radius (Used only for Agglomerata Type mesh)
*       set Thin film thickness [cm] = 10e-7           # Agglomerate thin film (Used only for Agglomerata Type mesh)
*     end
*
*     subsection Mesh refinement parameters
*       set Initial vertical cell count = 6            # Number of cells we want in the y-dir of the original grid before starting to solve"
*       set Horizontal division of cathode GDL = 4     # Number of cells we want horizontally in the cathode GDL layer
*       set Horizontal division of cathode CL = 1      # Number of cells we want horizontally in the cathode CL layer
*       set Horizontal division of cathode MPL = 1     # Number of cells we want horizontally in the cathode MPL layer
*       set Horizontal division of membrane = 2        # Number of cells we want horizontally in the membrane layer
*       set Horizontal division of anode MPL = 1       # Number of cells we want horizontally in the anode MPL layer
*       set Horizontal division of anode CL = 1        # Number of cells we want horizontally in the anode CL layer
*       set Horizontal division of anode GDL = 4       # Number of cells we want horizontally in the anode GDL layer
*     end
*
*     subsection Material ID
*       set Test = 1                                    # Material id for GridTest
*       set Cathode current collector = 0               # Current collector material_id
*       set Cathode gas channel = 1                     # Cathode gas channel material_id
*       set Cathode GDL = 2                             # Cathode gas diffusion layer material_id
*       set Cathode MPL = 3                             # Cathode microporous layer material_id
*       set Cathode CL = 4                              # Cathode catalyst layer material_id
*       set Membrane = 5                                # Membrane material_id
*       set Anode MPL = 7                               # Anode microporous layer material_id
*       set Anode CL = 6                                # Anode catalyst layer material_id
*       set Anode GDL = 8                               # Anode gas diffusion layer material_id
*       set Anode gas channel = 9                       # Anode gas channel material_id
*       set Anode current collector = 10                # Anode current collector material_id
*       set Agglomerate Material ID = 1
*       set Thin Film Material ID = 2
*     end
*     subsection Boundary ID
*       # NOTE: 255 defines an interior boundary conditions in deal.II. All internal boundaries
*       # MUST have a 255 boundary id.
*       set c_Ch/GDL = 100                              # Cathode gas channel and gas diffusion layer boundary_id
*       set c_BPP/GDL = 200                             # Cathode bipolar plates and gas diffusion layer boundary_id
*       set c_GDL/CL= 255                               # Cathode gas diffusion layer and catalyst layer boundary_id
*       set c_CL/Membrane = 400                         # Cathode catalyst layer and membrane boundary_id
*       set c_GDL/MPL = 255                             # Cathode gas diffusion layer and microporous layer boundary_id
*       set c_MPL/CL = 255                              # Cathode microporous layer and catalyst layer boundary_id
*       set c_CL/Membrane = 255                         # Cathode catalyst layer and membrane boundary_id
*       set Membrane/a_CL = 255                         # Membrane and anode catalyst layer boundary_id
*       set a_CL/GDL = 255                              # Anode catalyst layer and gas diffusion layer boundary_id
*       set a_CL/MPL = 255                              # Anode catalyst layer and microporous layer boundary_id
*       set a_MPL/GDL = 255                             # Anode microporous layer and gas diffusion layer boundary_id
*       set a_GDL/BPP = 3                               # Anode gas diffusion layer and bipolar plate boundary_id
*       set a_GDL/Ch = 4                                # Anode gas diffusion layer and channel boundary_id
*       set Agglomerate-Thin Film Boundary ID = 255
*       set Thin Film Boundary ID = 0
*     end
*   end
* end
*
template<int dim> virtual void FuelCellShop::Geometry::GridBase< dim >::generate_grid (Triangulation< dim > &) inline virtual
Function is empty and must be reimplemented in derived classes.
Reimplemented in FuelCellShop::Geometry::GridTest< dim >, FuelCellShop::Geometry::Agglomerate< dim >, FuelCellShop::Geometry::PemfcMPL< dim >, FuelCellShop::Geometry::CathodeMPL< dim >, FuelCellShop::Geometry::HyperCube< dim >, and FuelCellShop::Geometry::GridExternal< dim >.
References FcstUtilities::log.
template<int dim> void FuelCellShop::Geometry::GridBase< dim >::generate_grid_with_curved_boundaries (Triangulation< dim > & triangulation, const types::boundary_id & bdry_id, boost::shared_ptr< Boundary< dim > > boundary) const inline
This function is like the previous one generate_grid() but allows to assign a curved boundary boundary to that with the boundary id bdry_id.
References FcstUtilities::log.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::get_boundary_id (ParameterHandler & param, const std::string boundary) const
Return boundary id.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::get_boundary_id (const std::string) const
Return boundary id.
template<int dim> static _mapFactory* FuelCellShop::Geometry::GridBase< dim >::get_mapFactory () inline static protected
Referenced by FuelCellShop::Geometry::Agglomerate< dim >::Agglomerate(), FuelCellShop::Geometry::CathodeMPL< dim >::CathodeMPL(), FuelCellShop::Geometry::GridBase< dim >::create_GridGenerator(), FuelCellShop::Geometry::GridExternal< dim >::GridExternal(), FuelCellShop::Geometry::GridTest< dim >::GridTest(), FuelCellShop::Geometry::HyperCube< dim >::HyperCube(), and FuelCellShop::Geometry::PemfcMPL< dim >::PemfcMPL().
template<int dim> std::vector<unsigned int> FuelCellShop::Geometry::GridBase< dim >::get_material_id (const std::string) const
Return a vector with all material ids associated with string.
Note
For composite layers this will be more than one value.
template<int dim> std::string FuelCellShop::Geometry::GridBase< dim >::get_mesh_type () inline
Return the type of mesh that is being used.
Options: GridExternal | CathodeMPL | PemfcMPL
template<int dim> void FuelCellShop::Geometry::GridBase< dim >::initialize (ParameterHandler & param) protected
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_cat_a () inline
Return the Thickness of the anode catalyst layer.
template<int dim> std::vector<double> FuelCellShop::Geometry::GridBase< dim >::L_cat_c () inline
Return the thickness of the cathode catalyst layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channel_a () inline
Return the Width of the anode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channel_c () inline
Return the Width of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channelEntrance_c () inline
Return the Entrance Length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channelExit_c () inline
Return the Exit Length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channelHeight_c () inline
Return the Height of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_channelLength_c () inline
Return the Length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_gdl_a () inline
Return the Thickness of the anode gas diffusion layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_gdl_c () inline
Return the Thickness of the cathode gas diffusion layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_land_a () inline
Return the Width of the anode current collector.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_land_c () inline
Return the Width of the cathode current collector.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_mem () inline
Return the Thickness of the membrane.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_mpl_a () inline
Return the Thickness of the anode microporous layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::L_mpl_c () inline
Return the Thickness of the cathode microporous layer.
template<int dim> void FuelCellShop::Geometry::GridBase< dim >::output_grid (const Triangulation< dim > & triangulation, const std::string filename) const
Output the grid.
template<int dim> void FuelCellShop::Geometry::GridBase< dim >::print_material_id_and_boundary_id (const Triangulation< dim > & triangulation) const protected
template<int dim> void FuelCellShop::Geometry::GridBase< dim >::refine_area (Triangulation< dim > & triangulation, const unsigned int material_id)
Refine a certain part of the grid depending on material_ID given.
Member Data Documentation
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_CC_mid protected
Material id anode current collector.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_Ch_base_bid protected
Boundary id cathode channel entrance/exit base.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_Ch_Inlet_bid protected
Boundary id cathode channel inlet.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_Ch_Outlet_bid protected
Boundary id cathode channel outlet.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_Ch_roof_bid protected
Boundary id cathode channel entrance/exit roof.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_CL_GDL_bid protected
Boundary id anode CL and GDL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_CL_mid protected
Material id anode catalyst layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_CL_MPL_bid protected
Boundary id anode MPL and CL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_GC_mid protected
Material id anode gas channel.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_GDL_BPP_bid protected
Boundary id anode GDL and BPP.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_GDL_Ch_bid protected
Boundary id anode GDL and channel.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_GDL_mid protected
Material id anode GDL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_Membrane_CL_bid protected
Boundary id anode membrane and CL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_MPL_GDL_bid protected
Boundary id anode GDL and MPL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::a_MPL_mid protected
Material id anode MPL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_BPP_GDL_bid protected
Boundary id cathode BPP and GDL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_CC_mid protected
Material id cathode current collector.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_Ch_base_bid protected
Boundary id cathode channel entrance/exit base.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_Ch_GDL_bid protected
Boundary id cathode channel and GDL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_Ch_Inlet_bid protected
Boundary id cathode channel inlet.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_Ch_Outlet_bid protected
Boundary id cathode channel outlet.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_Ch_roof_bid protected
Boundary id cathode channel entrance/exit roof.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_CL_Membrane_bid protected
Boundary id cathode CL and membrane.
template<int dim> std::vector<unsigned int> FuelCellShop::Geometry::GridBase< dim >::c_CL_mid protected
Material id cathode catalyst layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_GC_mid protected
Material id cathode gas channel.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_GDL_CL_bid protected
Boundary id cathode GDL and CL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_GDL_mid protected
Material id cathode GDL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_GDL_MPL_bid protected
Boundary id cathode GDL and MPL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_MPL_CL_bid protected
Boundary id cathode MPL and CL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::c_MPL_mid protected
Material id cathode MPL.
template<int dim> Point<dim> FuelCellShop::Geometry::GridBase< dim >::center protected
Centre point of the circular/spherical domain.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::delta_agg protected
Electrolyte thin film thickness.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::delta_agg_mid protected
Electrolyte Thin Film Material ID.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::delta_bid protected
Boundary ID for thin film external boundary.
template<int dim> boost::shared_ptr<GridIn<dim> > FuelCellShop::Geometry::GridBase< dim >::grid_in
GridIn class object of dealii which allows to read various types of mesh formats.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_cat_a protected
Thickness of the anode catalyst layer.
template<int dim> std::vector<double> FuelCellShop::Geometry::GridBase< dim >::l_cat_c protected
Thickness of the cathode catalyst layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channel_a protected
Width of the anode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channel_c protected
Width of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channelEntrance_c protected
Entrance length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channelExit_c protected
Exit Length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channelHeight_c protected
Height of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_channelLength_c protected
Length of the cathode gas channel.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_cube protected
Cube edge for HyperCube mesh.
Cube will go from -l_cube to l_cube
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_gdl_a protected
Thickness of the anode gas diffusion layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_gdl_c protected
Thickness of the cathode gas diffusion layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_land_a protected
Width of the anode current collector.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_land_c protected
Width of the cathode current collector.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_mem protected
Thickness of the membrane.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_mpl_a protected
Thickness of the anode microporous layer.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::l_mpl_c protected
Thickness of the cathode microporous layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::membrane_mid protected
Material id membrane.
template<int dim> std::string FuelCellShop::Geometry::GridBase< dim >::mesh_name protected
Name of the mesh file.
template<int dim> std::string FuelCellShop::Geometry::GridBase< dim >::mesh_type protected
Specify if it is a UNV file, MSH file, etc.
template<int dim> std::string FuelCellShop::Geometry::GridBase< dim >::mesh_type_name protected
Specify if you would like to load a mesh from file or if you would like a module from the mesh generator Options: File | Cathode | Anode | CathodeMPL | Pemfc | PemfcMPL.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_a_CL protected
Number of cells wide anode catalyst layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_a_GDL protected
Number of cells wide anode gas diffusion layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_a_MPL protected
Number of cells wide anode microporous layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_c_Channel protected
Number of cells wide cathode channel.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_c_CL protected
Number of cells wide cathode catalyst layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_c_GDL protected
Number of cells wide cathode gas diffusion layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_c_MPL protected
Number of cells wide cathode microporous layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_membrane protected
Number of cells wide membrane layer.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_refine protected
Initial number of refinements.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::num_vert protected
Number of cells tall the initial grid.
template<int dim> double FuelCellShop::Geometry::GridBase< dim >::r_agg protected
Agglomerate radius.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::r_agg_mid protected
Porous Agglomerate Material ID.
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::r_delta_bid protected
Boundary ID for agglomerate/thin film boundary.
template<int dim> bool FuelCellShop::Geometry::GridBase< dim >::read_from_file
template<int dim> unsigned int FuelCellShop::Geometry::GridBase< dim >::test_mid protected
Material id for test cell (GridTest app)
The documentation for this class was generated from the following file:
geometry.h