OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Equation::ReactionHeat Class Reference
FuelCellShop::Equation::ReactionHeat Class Reference
This class is used to compute non-linear reaction heat source terms in a catalyst layer.
#include <reaction_heat.h>
Public Member Functions
Constructor, Destructor and Initialization
ReactionHeat ()
Constructor.
~ReactionHeat ()
Destructor.
void set_kinetics (FuelCellShop::Kinetics::BaseKinetics *kin)
Function to set Kinetics for enabling calculation source terms.
Initialization methods for computation
void set_electrolyte_potential (const SolutionVariable &phi)
Set the electrolyte phase potential.
void set_solid_potential (const SolutionVariable &phi)
Set the solid phase potential.
void set_temperature (const SolutionVariable &temperature)
Set temperature.
void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the variables for which we would like to compute the derivatives.
void initialize_factors (const bool &flag_irrev_ORR=true, const bool &flag_irrev_HOR=true, const bool &flag_rev_heat=true, const double &rev_heat_ORR_coef=1.0, const bool &flag_single_phase_ORR=true)
Method to initialize the flags and factors corresponding to various source term components in the application.
Source term computation methods
void heat_source (std::vector< double > &heat, const std::vector< double > &current) const
Member function that computes the non-linear thermal source terms, as a first argument by reference.
void derivative_heat_source (std::map< VariableNames, std::vector< double > > &heat_derived, const std::map< VariableNames, std::vector< double > > &current_derived, const std::vector< double > &current) const
Member function that computes the derivative of the source terms with respect to the solution variables/parameters set using set_derivative_flags method.
Internal data and methods
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives which are computed using the derivative_heat_source function.
FuelCellShop::Kinetics::BaseKinetics * kinetics
Store pointer to the kinetics object.
SolutionVariable phi_m
Struct storing a pointer to the solution vector for the electrolyte potential.
SolutionVariable phi_s
Struct stroing a pointer to the solution vector for the electronic/solid potential.
SolutionVariable T
Struct stroing a pointer to the solution vector for the temperature.
double factor_irrev_ORR
Factor for irreversible heating in ORR.
double factor_irrev_HOR
Factor for irreversible heating in HOR.
double factor_rev_ORR
Factor for reversible heating in ORR.
double factor_rev_HOR
Factor for reversible heating in HOR.
double factor_vap_ORR
Factor for water vaporization heat sink in ORR.
bool factors_initialized
Flag to check whether factors are initialized or not.
double entropy_rxn (const double &Temp) const
Function to compute entropy change of reaction [J/(mol-K)] as a function of temperature [K].
double deriv_entropy_rxn (const double &Temp) const
Function to compute derivative of entropy change of reaction with respect to temperature [K].
Detailed Description
This class is used to compute non-linear reaction heat source terms in a catalyst layer.
There are basically two sources of heat generation for an electro-chemical reaction. These are: Reversible Heat and Irreversible Heat
Besides this, there is an additional heat sink, accounting for complete evaporation of liquid water formed inside the Cathode catalyst layer (ORR). This is done to maintain consistency with single phase formulation.
The can be written in following three components for ORR:
Similarly, the can be written for HOR:
where,
is current density [A/cm^3], retrieved from kinetics object.
is Entropy change for overall reaction forming liquid water product and is a function of Temperature().
is Latent heat of vaporization of water and is a function of Temperature().
and are the fractions of overall entropic heat released, corresponding to half-cell reactions of ORR and HOR respectively. They are defined such that: .
Remarks
Following points to be noted:
Overpotential () is negative for ORR (Cathode side). Hence, a negative sign is included in the formulation.
Similarly, entropy change () for an exothermic reaction (ORR) is negative, hence a negative sign.
There is no water formation in HOR (Anode side), hence no water vaporization inside the anode catalyst layer.
This class computes heat source in W/cm^3 and its derivatives.
Note
This class requires atleast these three solution variables, viz., (Electronic electric potential), (Protonic electric potential), and, (Temperature) to be set using set_solid_potential, set_electrolyte_potential and set_temperature methods respectively, in order to compute heat source terms (heat_source) and their derivatives (derivative_heat_source).
It is necessary to call initialize_factors method to set the corresponding heat source flags before computing heat source terms or their derivatives.
Also kinetics object is required to be set using set_kinetics method in the initialization section of application/equation.
Author
Madhur Bhaiya, 2012-2013
Constructor & Destructor Documentation
FuelCellShop::Equation::ReactionHeat::ReactionHeat ()
Constructor.
FuelCellShop::Equation::ReactionHeat::~ReactionHeat ()
Destructor.
Member Function Documentation
double FuelCellShop::Equation::ReactionHeat::deriv_entropy_rxn (const double & Temp) const inline protected
Function to compute derivative of entropy change of reaction with respect to temperature [K].
void FuelCellShop::Equation::ReactionHeat::derivative_heat_source (std::map< VariableNames, std::vector< double > > & heat_derived, const std::map< VariableNames, std::vector< double > > & current_derived, const std::vector< double > & current) const
Member function that computes the derivative of the source terms with respect to the solution variables/parameters set using set_derivative_flags method.
This function takes the current [A/cm^3] and its derivatives computed from the catalyst layer object, as const third and second arguments respectively. It is also necessary to ensure that the derivative_flags set inside this object should atleast be there inside the derivative current map. The derivative of heat source is returned by reference in the first argument as a map.
double FuelCellShop::Equation::ReactionHeat::entropy_rxn (const double & Temp) const inline protected
Function to compute entropy change of reaction [J/(mol-K)] as a function of temperature [K].
Ref: G. Lewis and M. Randall. International Critical Tables, volum 7. McGraw Hill, New York, 1930.
References FcstUtilities::log.
void FuelCellShop::Equation::ReactionHeat::heat_source (std::vector< double > & heat, const std::vector< double > & current) const
Member function that computes the non-linear thermal source terms, as a first argument by reference.
This function takes the current [A/cm^3] computed from the catalyst layer object, as a const second argument.
void FuelCellShop::Equation::ReactionHeat::initialize_factors (const bool & flag_irrev_ORR = true, const bool & flag_irrev_HOR = true, const bool & flag_rev_heat = true, const double & rev_heat_ORR_coef = 1.0, const bool & flag_single_phase_ORR = true) inline
Method to initialize the flags and factors corresponding to various source term components in the application.
This method should normally be initialization of the application/equation class. It takes following arguments:
flag_irrev_ORR is for Irreversible heat generation in ORR, defaulted to TRUE.
flag_irrev_HOR is for Irreversible heat generation in HOR, defaulted to TRUE.
flag_rev_heat is for Reversible heat generation in the overall reaction forming liquid water product, defaulted to TRUE.
rev_heat_ORR_coef is for fraction of reversible heat released in the half-cell reaction of ORR, defaulted to 1.0 (i.e., complete reversible (entropic) heat is released in the ORR).
flag_single_phase_ORR is for complete vaporization of liquid water formed during ORR, defaulted to TRUE.
References Constants::F().
void FuelCellShop::Equation::ReactionHeat::set_derivative_flags (const std::vector< VariableNames > & flags) inline
Set the variables for which we would like to compute the derivatives.
void FuelCellShop::Equation::ReactionHeat::set_electrolyte_potential (const SolutionVariable & phi) inline
Set the electrolyte phase potential.
The potential should be in Volts.
References FuelCellShop::SolutionVariable::get_variablename(), and protonic_electrical_potential.
void FuelCellShop::Equation::ReactionHeat::set_kinetics (FuelCellShop::Kinetics::BaseKinetics * kin) inline
Function to set Kinetics for enabling calculation source terms.
void FuelCellShop::Equation::ReactionHeat::set_solid_potential (const SolutionVariable & phi) inline
Set the solid phase potential.
The potential should be in Volts.
References electronic_electrical_potential, and FuelCellShop::SolutionVariable::get_variablename().
void FuelCellShop::Equation::ReactionHeat::set_temperature (const SolutionVariable & temperature) inline
Set temperature.
The temperature should be in Kelvin.
References FuelCellShop::SolutionVariable::get_variablename(), and temperature_of_REV.
Member Data Documentation
std::vector<VariableNames> FuelCellShop::Equation::ReactionHeat::derivative_flags protected
Flags for derivatives: These flags are used to request derivatives which are computed using the derivative_heat_source function.
double FuelCellShop::Equation::ReactionHeat::factor_irrev_HOR protected
Factor for irreversible heating in HOR.
double FuelCellShop::Equation::ReactionHeat::factor_irrev_ORR protected
Factor for irreversible heating in ORR.
double FuelCellShop::Equation::ReactionHeat::factor_rev_HOR protected
Factor for reversible heating in HOR.
double FuelCellShop::Equation::ReactionHeat::factor_rev_ORR protected
Factor for reversible heating in ORR.
double FuelCellShop::Equation::ReactionHeat::factor_vap_ORR protected
Factor for water vaporization heat sink in ORR.
bool FuelCellShop::Equation::ReactionHeat::factors_initialized protected
Flag to check whether factors are initialized or not.
FuelCellShop::Kinetics::BaseKinetics* FuelCellShop::Equation::ReactionHeat::kinetics protected
Store pointer to the kinetics object.
SolutionVariable FuelCellShop::Equation::ReactionHeat::phi_m protected
Struct storing a pointer to the solution vector for the electrolyte potential.
SolutionVariable FuelCellShop::Equation::ReactionHeat::phi_s protected
Struct stroing a pointer to the solution vector for the electronic/solid potential.
SolutionVariable FuelCellShop::Equation::ReactionHeat::T protected
Struct stroing a pointer to the solution vector for the temperature.
The documentation for this class was generated from the following file:
reaction_heat.h