OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Kinetics::BaseKinetics Class Reference
FuelCellShop::Kinetics::BaseKinetics Class Reference abstract
Virtual class used to provide the interface for all kinetic/reaction children.
#include <base_kinetics.h>
Public Member Functions
virtual ~BaseKinetics ()
Destructor.
virtual bool has_coverage (const VariableNames &type)
Initalization
void set_electrolyte_potential (const SolutionVariable &phi)
Set the electrolyte phase potential.
void set_solid_potential (const SolutionVariable &phi)
Set the solid phase potential.
void set_temperature (const SolutionVariable &temperature)
Set temperature.
void set_reactant_concentrations (const std::vector< SolutionVariable > &conc_vec)
Set reactant concentrations at the catalyst/electrolyte interface.
void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the variables for which you would like to compute the derivaitives.
void set_catalyst (FuelCellShop::Material::CatalystBase *cat_in)
Set a pointer to the catalyst that will be used.
void set_electrolyte (FuelCellShop::Material::PolymerElectrolyteBase *electrolyte_in)
Member function used to set the electrolyte pointer to that used by the application.
virtual void set_reaction_kinetics (const ReactionNames name)
Member function used to specify the reaction for which the kinetic parameters are needed, for example for a Platinum catalyst, we can specify that we need the kinetic parameters for either the oxygen reduction reaction (ORR) or the hydrogen oxidation reaction (HOR)
void set_p_t (const double &P_Tot)
Set the total gas pressure [Pascals] in the cell.
Information and accessors
ReactionNames get_reaction_name () const
Returns the name of the reaction that this kinetics class is using.
FuelCellShop::Material::CatalystBase * get_cat () const
Function to get pointer to catalyst class.
virtual void current_density (std::vector< double > &)
Function to return the value of the current [A/cm^2].
virtual void derivative_current (std::map< VariableNames, std::vector< double > > &)
Function to return the derivative of the current density w.r.t solution variables.
virtual void compute_coverages (const std::string &name_species, std::vector< double > &coverage) const
Used to return the coverage of the intermediate species if they are computed.
virtual void OH_coverage (std::vector< double > &) const
Used to return the coverage of the intermediate species if they are computed.
virtual void O_coverage (std::vector< double > &) const
Used to return the coverage of the intermediate species if they are computed.
Static Public Member Functions
Instance Delivery (Public functions)
static void declare_Kinetics_parameters (ParameterHandler &param)
Function used to declare all the data necessary in the parameter files for all BaseKinetics children.
static boost::shared_ptr
< FuelCellShop::Kinetics::BaseKinetics > create_Kinetics (ParameterHandler &param, std::string kinetics_name)
Function called in create_CatalystLayer and used to select the appropriate BaseKinetics type that will be used in the layer.
Protected Types
Instance Delivery (Types)
typedef std::map< std::string,
BaseKinetics * > _mapFactory
This object is used to store all objects of type BaseKinetics.
Protected Member Functions
Instance Delivery (Private functions)
virtual boost::shared_ptr
< FuelCellShop::Kinetics::BaseKinetics > create_replica ()
This member function is used to create an object of type BaseKinetics.
Constructors, destructor, and initalization
BaseKinetics ()
Constructor.
virtual void declare_parameters (ParameterHandler &) const
Declare parameters for a parameter file.
virtual void initialize (ParameterHandler &)
Member function used to read in data and initialize the necessary data to compute the coefficients.
Static Protected Member Functions
Instance Delivery (Private and static)
static _mapFactory * get_mapFactory ()
Protected Attributes
Universal constants
double R
Universal gas constant.
double F
Universal Farday's constant.
double K
Boltzmann constant.
Solution variables
double p_total
Total gas pressure [Pascals] in the cell for isobaric case.
std::map< VariableNames,
SolutionVariable > reactants_map
Map of SolutionVariables storing a pointer to the solution vector storing the concentration of each one of the reactants implemented.
SolutionVariable phi_m
Struct storing a pointer to the solution vector for the electrolyte potential.
SolutionVariable phi_s
Struct stroing a pointer to the solution vector for the electronic/solid potential.
SolutionVariable T
Struct stroing a pointer to the solution vector for the temperature.
Material objects and other internal data/methods
bool kin_param_initialized
Boolean variable to determine whether init_kin_param has been already called or not.
ReactionNames name_reaction_kinetics
Enumeration with the reaction name for which the class returns kinetic parameters.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives which are computed using the derivative_current function.
unsigned int n_quad
Number of quadrature points in the cell.
FuelCellShop::Material::CatalystBase * catalyst
Pointer to the catalyst object that is created at the application level and passed to the kinetics class using the set_catalyst function.
FuelCellShop::Material::PolymerElectrolyteBase * electrolyte
Pointer to the electrolyte object created in the application that is used to calculate the properties of the electrolyte in the catalyst layer.
virtual void init_kin_param ()=0
Pure abstract method used to initialize certain kinetics parameters which are normally constant, e.g.
Detailed Description
Virtual class used to provide the interface for all kinetic/reaction children.
The main purpose of kinetic objects is to calculate the rate of the reaction. In the case of fuel cells, instead of the rate we return the current that is produced per unit area of catalyst in the electrode.
To use this class, first the object needs to be initialized by doing two very important things:
Assign the materials to be used by the class using the member functions: set_catalyst and set_electrolyte
Initialize the solution variables using the member functions: set_electrolyte_potential, set_solid_potential and so on.
No object of type BaseKinetics should ever be created, instead this class is used to initialize pointers of type BaseKinetics and to provide a common interface for all Kinetics classes.
The class has a database of children such that it will declare all necessary parameters for all children in the input file, read the input file, create the appropriate children and return a pointer to BaseKinetics with the children selected.
Usage Details:
In order to create a kinetics object within an reactive layer, the following steps need to be taken.
First, in the CatalystLayer object .h file that needs a kinetics object, create a pointer to a BaseKinetics object, i.e.
* boost::shared_ptr<FuelCellShop::Kinetics::BaseKinetics<dim> >ORR;
*
This pointer object will be available anywhere inside the reactive layer. Because we do not want to worry about deleting the pointer afterwards, we use a Boost pointer which has its own memory management algorithms. See the Boost website for more information
Once the pointer is available, we need to do three things in the reactive layer
Call declare_Kinetics_parameters in the reactive layer declare_parameters() member function. This member function is used to define all parameters that can be read from the input file
Call create_Kinetics and initialize. The former member function will fill the pointer created above with the appropriate gas diffusion layer you have selected in the input file. Then, initialize reads from the input file all the data from the file in order to setup the object.
The object is ready for use now.
For a code example see unit_tests/source/DT_test.cc.
Author
M. Moore, 2011-12
M. Bhaiya, 2013
M. Secanell, 2013
Member Typedef Documentation
typedef std::map< std::string, BaseKinetics* > FuelCellShop::Kinetics::BaseKinetics::_mapFactory protected
This object is used to store all objects of type BaseKinetics.
Constructor & Destructor Documentation
virtual FuelCellShop::Kinetics::BaseKinetics::~BaseKinetics () inline virtual
Destructor.
FuelCellShop::Kinetics::BaseKinetics::BaseKinetics () inline protected
Constructor.
References Constants::F(), Constants::K(), and Constants::R().
Member Function Documentation
virtual void FuelCellShop::Kinetics::BaseKinetics::compute_coverages (const std::string & name_species, std::vector< double > & coverage) const inline virtual
Used to return the coverage of the intermediate species if they are computed.
References FcstUtilities::log.
static boost::shared_ptr<FuelCellShop::Kinetics::BaseKinetics > FuelCellShop::Kinetics::BaseKinetics::create_Kinetics (ParameterHandler & param, std::string kinetics_name) inline static
Function called in create_CatalystLayer and used to select the appropriate BaseKinetics type that will be used in the layer.
The name of the kinetics object to be used is provided in kinetics_name.
The name of the kinetics object is provided in the ParameterHandler in the CatalystLayer subsection as follows:
* subsection Catalyst Layer Properties <- This name is the name of the catalyst layer subsection where the kinetics are taking place.
* (...)
*   set Kinetics type = TafelKinetics
* (...)
* end
*
current options are [ TafelKinetics | DoubleTrapKinetics | DualPathKinetics | BVKinetics ]
References get_mapFactory(), and FcstUtilities::log.
virtual boost::shared_ptr<FuelCellShop::Kinetics::BaseKinetics > FuelCellShop::Kinetics::BaseKinetics::create_replica () inline protected virtual
This member function is used to create an object of type BaseKinetics.
Warning
This class MUST be redeclared in every child.
Reimplemented in FuelCellShop::Kinetics::DoubleTrapKinetics, FuelCellShop::Kinetics::DualPathKinetics, FuelCellShop::Kinetics::TafelKinetics, and FuelCellShop::Kinetics::ButlerVolmerKinetics.
References FcstUtilities::log.
virtual void FuelCellShop::Kinetics::BaseKinetics::current_density (std::vector< double > &) inline virtual
Function to return the value of the current [A/cm^2].
Reimplemented in FuelCellShop::Kinetics::DualPathKinetics, FuelCellShop::Kinetics::TafelKinetics, FuelCellShop::Kinetics::DoubleTrapKinetics, and FuelCellShop::Kinetics::ButlerVolmerKinetics.
References FcstUtilities::log.
static void FuelCellShop::Kinetics::BaseKinetics::declare_Kinetics_parameters (ParameterHandler & param) inline static
Function used to declare all the data necessary in the parameter files for all BaseKinetics children.
References get_mapFactory().
virtual void FuelCellShop::Kinetics::BaseKinetics::declare_parameters (ParameterHandler &) const inline protected virtual
Declare parameters for a parameter file.
Reimplemented in FuelCellShop::Kinetics::ButlerVolmerKinetics, FuelCellShop::Kinetics::DoubleTrapKinetics, FuelCellShop::Kinetics::DualPathKinetics, and FuelCellShop::Kinetics::TafelKinetics.
References FcstUtilities::log.
virtual void FuelCellShop::Kinetics::BaseKinetics::derivative_current (std::map< VariableNames, std::vector< double > > &) inline virtual
Function to return the derivative of the current density w.r.t solution variables.
It returns a map of vectors containing derivative w.r.t solution variables / design variables set using set_derivative_flags method. Each vector can be accessed by using Key of the map, which correpsonds to the VariableNames (solution/design variable). This method takes input map by reference, hence the map is needed to be created at application/equation level with default arguments and passed inside this method.
Reimplemented in FuelCellShop::Kinetics::DualPathKinetics, FuelCellShop::Kinetics::TafelKinetics, FuelCellShop::Kinetics::DoubleTrapKinetics, and FuelCellShop::Kinetics::ButlerVolmerKinetics.
References FcstUtilities::log.
FuelCellShop::Material::CatalystBase* FuelCellShop::Kinetics::BaseKinetics::get_cat () const inline
Function to get pointer to catalyst class.
This function is basically needed by thermal source class.
static _mapFactory* FuelCellShop::Kinetics::BaseKinetics::get_mapFactory () inline static protected
Referenced by create_Kinetics(), and declare_Kinetics_parameters().
ReactionNames FuelCellShop::Kinetics::BaseKinetics::get_reaction_name () const inline
Returns the name of the reaction that this kinetics class is using.
virtual bool FuelCellShop::Kinetics::BaseKinetics::has_coverage (const VariableNames & type) inline virtual
Reimplemented in FuelCellShop::Kinetics::DoubleTrapKinetics.
virtual void FuelCellShop::Kinetics::BaseKinetics::init_kin_param () protected pure virtual
Pure abstract method used to initialize certain kinetics parameters which are normally constant, e.g.
reference concentrations, reaction order etc. This function is necessarily required to be reimplemented in all of the child kinetics classes.
Implemented in FuelCellShop::Kinetics::DoubleTrapKinetics, FuelCellShop::Kinetics::DualPathKinetics, FuelCellShop::Kinetics::TafelKinetics, and FuelCellShop::Kinetics::ButlerVolmerKinetics.
virtual void FuelCellShop::Kinetics::BaseKinetics::initialize (ParameterHandler &) inline protected virtual
Member function used to read in data and initialize the necessary data to compute the coefficients.
Reimplemented in FuelCellShop::Kinetics::ButlerVolmerKinetics, FuelCellShop::Kinetics::DoubleTrapKinetics, FuelCellShop::Kinetics::DualPathKinetics, and FuelCellShop::Kinetics::TafelKinetics.
References FcstUtilities::log.
virtual void FuelCellShop::Kinetics::BaseKinetics::O_coverage (std::vector< double > &) const inline virtual
Used to return the coverage of the intermediate species if they are computed.
Deprecated:
Reimplemented in FuelCellShop::Kinetics::DoubleTrapKinetics.
References FcstUtilities::log.
virtual void FuelCellShop::Kinetics::BaseKinetics::OH_coverage (std::vector< double > &) const inline virtual
Used to return the coverage of the intermediate species if they are computed.
Deprecated:
Reimplemented in FuelCellShop::Kinetics::DoubleTrapKinetics.
References FcstUtilities::log.
void FuelCellShop::Kinetics::BaseKinetics::set_catalyst (FuelCellShop::Material::CatalystBase * cat_in) inline
Set a pointer to the catalyst that will be used.
The catalyst is specified at the application level and passed to the kinetics class using this function.
void FuelCellShop::Kinetics::BaseKinetics::set_derivative_flags (const std::vector< VariableNames > & flags) inline
Set the variables for which you would like to compute the derivaitives.
void FuelCellShop::Kinetics::BaseKinetics::set_electrolyte (FuelCellShop::Material::PolymerElectrolyteBase * electrolyte_in) inline
Member function used to set the electrolyte pointer to that used by the application.
Needed so that conversion from molar fraction to concentration can be done. (Henry's constant in particular is needed).
void FuelCellShop::Kinetics::BaseKinetics::set_electrolyte_potential (const SolutionVariable & phi) inline
Set the electrolyte phase potential.
The potential should be in Volts.
References FuelCellShop::SolutionVariable::get_variablename(), and protonic_electrical_potential.
void FuelCellShop::Kinetics::BaseKinetics::set_p_t (const double & P_Tot) inline
Set the total gas pressure [Pascals] in the cell.
void FuelCellShop::Kinetics::BaseKinetics::set_reactant_concentrations (const std::vector< SolutionVariable > & conc_vec) inline
Set reactant concentrations at the catalyst/electrolyte interface.
This should be the concentration in Nafion.
The concentrations should be in .
Warning
It should be ensured that no molar fractions are set using this method.
References hydrogen_molar_fraction, oxygen_molar_fraction, and water_molar_fraction.
virtual void FuelCellShop::Kinetics::BaseKinetics::set_reaction_kinetics (const ReactionNames name) inline virtual
Member function used to specify the reaction for which the kinetic parameters are needed, for example for a Platinum catalyst, we can specify that we need the kinetic parameters for either the oxygen reduction reaction (ORR) or the hydrogen oxidation reaction (HOR)
void FuelCellShop::Kinetics::BaseKinetics::set_solid_potential (const SolutionVariable & phi) inline
Set the solid phase potential.
The potential should be in Volts.
References electronic_electrical_potential, and FuelCellShop::SolutionVariable::get_variablename().
void FuelCellShop::Kinetics::BaseKinetics::set_temperature (const SolutionVariable & temperature) inline
Set temperature.
The temperature should be in Kelvin.
References FuelCellShop::SolutionVariable::get_variablename(), and temperature_of_REV.
Member Data Documentation
FuelCellShop::Material::CatalystBase* FuelCellShop::Kinetics::BaseKinetics::catalyst protected
Pointer to the catalyst object that is created at the application level and passed to the kinetics class using the set_catalyst function.
std::vector<VariableNames> FuelCellShop::Kinetics::BaseKinetics::derivative_flags protected
Flags for derivatives: These flags are used to request derivatives which are computed using the derivative_current function.
FuelCellShop::Material::PolymerElectrolyteBase* FuelCellShop::Kinetics::BaseKinetics::electrolyte protected
Pointer to the electrolyte object created in the application that is used to calculate the properties of the electrolyte in the catalyst layer.
double FuelCellShop::Kinetics::BaseKinetics::F protected
Universal Farday's constant.
double FuelCellShop::Kinetics::BaseKinetics::K protected
Boltzmann constant.
bool FuelCellShop::Kinetics::BaseKinetics::kin_param_initialized protected
Boolean variable to determine whether init_kin_param has been already called or not.
unsigned int FuelCellShop::Kinetics::BaseKinetics::n_quad protected
Number of quadrature points in the cell.
ReactionNames FuelCellShop::Kinetics::BaseKinetics::name_reaction_kinetics protected
Enumeration with the reaction name for which the class returns kinetic parameters.
double FuelCellShop::Kinetics::BaseKinetics::p_total protected
Total gas pressure [Pascals] in the cell for isobaric case.
SolutionVariable FuelCellShop::Kinetics::BaseKinetics::phi_m protected
Struct storing a pointer to the solution vector for the electrolyte potential.
SolutionVariable FuelCellShop::Kinetics::BaseKinetics::phi_s protected
Struct stroing a pointer to the solution vector for the electronic/solid potential.
double FuelCellShop::Kinetics::BaseKinetics::R protected
Universal gas constant.
std::map< VariableNames, SolutionVariable > FuelCellShop::Kinetics::BaseKinetics::reactants_map protected
Map of SolutionVariables storing a pointer to the solution vector storing the concentration of each one of the reactants implemented.
SolutionVariable FuelCellShop::Kinetics::BaseKinetics::T protected
Struct stroing a pointer to the solution vector for the temperature.
The documentation for this class was generated from the following file:
base_kinetics.h