OpenFCST: The open-source Fuel Cell Simulation Toolbox: Constants Namespace Reference
Constants Namespace Reference
Functions
double R ()
Universal gas constant, .
double F ()
Faraday constant, .
double Pi ()
.
double E0 ()
Permittivity of free space, .
double K ()
Boltzmann constant, .
double K_SI ()
Boltzmann constant in SI units, .
double N_A ()
Avogadro's constant, .
const dealii::Tensor< 1, dim > gravity_acceleration ()
Gravitational acceleration, .
const dealii::SymmetricTensor
< 2, dim > unit_tensor ()
Unit tensor, .
double A_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double B_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double C_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double D_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double E_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double F_vk ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
double A_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double B_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double C_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double D_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double E_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double F_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double G_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double H_diff ()
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
double b_0 ()
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double b_1 ()
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double b_2 ()
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double b_3 ()
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double A11_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double B11_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double C11_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double D11_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double A11_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double B11_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double C11_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double D11_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double A22_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double B22_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double C22_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double D22_visc_R1 ()
Coefficient for the integrals formula (viscosity) between .
double A22_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double B22_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double C22_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
double D22_visc_R2 ()
Coefficient for the integrals formula (viscosity) between .
Function Documentation
double Constants::A11_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::A11_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::A22_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::A22_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::A_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::A_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::B11_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::B11_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::B22_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::B22_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::b_0 () inline
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double Constants::b_1 () inline
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double Constants::b_2 () inline
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double Constants::b_3 () inline
Coefficient of the Springer-Zawodzinski-Gottesfeld water vapor saturation pressure formula.
double Constants::B_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::B_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::C11_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::C11_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::C22_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::C22_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::C_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::C_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::D11_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::D11_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::D22_visc_R1 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::D22_visc_R2 () inline
Coefficient for the integrals formula (viscosity) between .
Kerkhof, Piet JAM, and Marcel AM Geboers. "Toward a unified theory of isotropic molecular transport phenomena." AIChE journal 51.1 (2005): 79-121.
Hirschfelder, Joseph O., et al. Molecular theory of gases and liquids. New York: Wiley, 1964.
double Constants::D_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::D_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::E0 () inline
Permittivity of free space, .
Referenced by FuelCellShop::MicroScale::AgglomerateBase::AgglomerateBase().
double Constants::E_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::E_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::F () inline
Faraday constant, .
Referenced by FuelCellShop::MicroScale::AgglomerateBase::AgglomerateBase(), FuelCellShop::Kinetics::BaseKinetics::BaseKinetics(), and FuelCellShop::Equation::ReactionHeat::initialize_factors().
double Constants::F_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::F_vk () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (viscosity and thermal conductivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::G_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
const dealii::Tensor<1,dim> Constants::gravity_acceleration () inline
Gravitational acceleration, .
References dim.
double Constants::H_diff () inline
Coefficient of the Neufeld-Jansen-Aziz collision integrals formula (diffusivity).
Neufeld, Philip D., A. R. Janzen, and R. A. Aziz. "Empirical Equations to Calculate 16 of the Transport Collision Integrals Ω (l, s)* for the Lennard‐Jones (12–6) Potential." The Journal of Chemical Physics 57.3 (1972): 1100-1102.
double Constants::K () inline
Boltzmann constant, .
Referenced by FuelCellShop::Kinetics::BaseKinetics::BaseKinetics().
double Constants::K_SI () inline
Boltzmann constant in SI units, .
double Constants::N_A () inline
Avogadro's constant, .
double Constants::Pi () inline
.
Referenced by FuelCellShop::MicroScale::SphericalAgglomerateGeometry::SphericalAgglomerateGeometry().
double Constants::R () inline
Universal gas constant, .
Referenced by FuelCellShop::MicroScale::AgglomerateBase::AgglomerateBase(), FuelCellShop::Kinetics::BaseKinetics::BaseKinetics(), FuelCell::OperatingConditions::get_anode_gas_density(), FuelCell::OperatingConditions::get_cathode_gas_density(), and FuelCellShop::Equation::LiquidSourceEquation< dim >::get_temp_related_parameters().
const dealii::SymmetricTensor<2,dim> Constants::unit_tensor () inline
Unit tensor, .
References dim.