OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Material::FiberBase Class Reference
FuelCellShop::Material::FiberBase Class Reference
#include <fiber_base.h>
Public Member Functions
FiberBase (std::string name)
Constructor The constructor initialize parameters using the default values.
~FiberBase ()
Destructor.
virtual void declare_parameters (ParameterHandler &param) const
Declare parameters.
virtual void set_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Set parameters on the parameter handler object.
virtual void initialize (ParameterHandler &param)
Initialize.
virtual double get_electrical_conductivity () const
Obtain the electrical conductivity.
virtual double get_electrical_conductivity (double) const
Obtain the temperature dependent electrical conductivity which is passed as the argument.
virtual double get_derivative_electrical_conductivity () const
virtual double get_thermal_conductivity () const
Obtain the thermal conductivity.
virtual double get_derivative_thermal_conductivity () const
virtual double get_density () const
Obtain the density.
Public Member Functions inherited from FuelCellShop::Material::BaseMaterial
void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the variables for which you would like to compute the derivatives.
const std::string & name_material ()
Return the name of the layer.
virtual void print_material_properties () const
This function prints out the material properties.
Protected Attributes
double electrical_conductivity
Electrical conductivity of carbon fibers extrapolated to 100% solid phase.
double thermal_conductivity
Thermal conductivity of carbon fibers extrapolated to 100% solid phase.
double density
Density of carbon fibers.
Protected Attributes inherited from FuelCellShop::Material::BaseMaterial
const std::string name
Name of the layer.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives.
Additional Inherited Members
Protected Member Functions inherited from FuelCellShop::Material::BaseMaterial
BaseMaterial ()
Constructor.
BaseMaterial (const std::string &name)
Constructor.
virtual ~BaseMaterial ()
Destructor.
Constructor & Destructor Documentation
FuelCellShop::Material::FiberBase::FiberBase (std::string name) inline
Constructor The constructor initialize parameters using the default values.
This is so that if I do not want to call declare_parameters and initialize, I can still use the routine with the hard coded values.
High Priority Todo:
What are we going to do with the Carbon, Nafion, Platinum, etc. classes? i.e. puresolids
FuelCellShop::Material::FiberBase::~FiberBase () inline
Destructor.
Member Function Documentation
virtual void FuelCellShop::Material::FiberBase::declare_parameters (ParameterHandler & param) const inline virtual
Declare parameters.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonFiber.
References FuelCellShop::Material::BaseMaterial::declare_parameters().
virtual double FuelCellShop::Material::FiberBase::get_density () const inline virtual
Obtain the density.
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual double FuelCellShop::Material::FiberBase::get_derivative_electrical_conductivity () const inline virtual
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual double FuelCellShop::Material::FiberBase::get_derivative_thermal_conductivity () const inline virtual
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual double FuelCellShop::Material::FiberBase::get_electrical_conductivity () const inline virtual
Obtain the electrical conductivity.
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual double FuelCellShop::Material::FiberBase::get_electrical_conductivity (double) const inline virtual
Obtain the temperature dependent electrical conductivity which is passed as the argument.
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual double FuelCellShop::Material::FiberBase::get_thermal_conductivity () const inline virtual
Obtain the thermal conductivity.
Reimplemented in FuelCellShop::Material::CarbonFiber.
virtual void FuelCellShop::Material::FiberBase::initialize (ParameterHandler & param) inline virtual
Initialize.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonFiber.
References FuelCellShop::Material::BaseMaterial::initialize().
virtual void FuelCellShop::Material::FiberBase::set_parameters (const std::vector< std::string > & name_dvar, const std::vector< double > & value_dvar, ParameterHandler & param) inline virtual
Set parameters on the parameter handler object.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonFiber.
References FuelCellShop::Material::BaseMaterial::set_parameters().
Member Data Documentation
double FuelCellShop::Material::FiberBase::density protected
Density of carbon fibers.
Referenced by FuelCellShop::Material::CarbonFiber::get_density().
double FuelCellShop::Material::FiberBase::electrical_conductivity protected
Electrical conductivity of carbon fibers extrapolated to 100% solid phase.
Referenced by FuelCellShop::Material::CarbonFiber::get_electrical_conductivity().
double FuelCellShop::Material::FiberBase::thermal_conductivity protected
Thermal conductivity of carbon fibers extrapolated to 100% solid phase.
Referenced by FuelCellShop::Material::CarbonFiber::get_thermal_conductivity().
The documentation for this class was generated from the following file:
fiber_base.h