OpenFCST: The open-source Fuel Cell Simulation Toolbox: FuelCellShop::Material::CatalystSupportBase Class Reference
FuelCellShop::Material::CatalystSupportBase Class Reference
This class implements the interface to compute the properties of a "standard" catalyst support.
#include <catalyst_support_base.h>
Public Member Functions
Information and accessors
virtual double get_electrical_conductivity () const
Obtain the electrical conductivity [S/cm].
virtual double get_thermal_conductivity () const
Obtain the thermal conductivity [W/(cm-K)].
virtual double get_density () const
Obtain the density [gm/cm^3].
Public Member Functions inherited from FuelCellShop::Material::BaseMaterial
void set_derivative_flags (const std::vector< VariableNames > &flags)
Set the variables for which you would like to compute the derivatives.
const std::string & name_material ()
Return the name of the layer.
virtual void print_material_properties () const
This function prints out the material properties.
Static Public Member Functions
Instance Delivery (Public functions)
static void declare_CatalystSupport_parameters (ParameterHandler &param)
Function used to declare all the data necessary in the parameter files for all CatalystSupportBase children.
static void set_CatalystSupport_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
static boost::shared_ptr
< FuelCellShop::Material::CatalystSupportBase > create_CatalystSupport (ParameterHandler &param, std::string support_name)
Function called in create_CatalystLayer and used to select the appropriate CatalystSupportBase children that will be used in the layer.
Protected Types
Instance Delivery (Types)
typedef std::map< std::string,
FuelCellShop::Material::CatalystSupportBase * > _mapFactory
This object is used to store all objects of type CatalystSupportBase.
Protected Member Functions
Constructors, destructor, and parameter initalization
CatalystSupportBase ()
Constructor.
CatalystSupportBase (std::string name)
Constructor The constructor initialize parameters using the default values.
~CatalystSupportBase ()
Destructor.
virtual void declare_parameters (ParameterHandler &param) const
Declare parameters for a parameter file.
virtual void set_parameters (const std::vector< std::string > &name_dvar, const std::vector< double > &value_dvar, ParameterHandler &param)
Member function used to change the values in the parameter file for a given list of parameters.
virtual void initialize (ParameterHandler &param)
Initialize parameters.
Instance Delivery (Private functions)
virtual boost::shared_ptr
< FuelCellShop::Material::CatalystSupportBase > create_replica ()
This member function is used to create an object of type CatalystSupportBase.
Protected Member Functions inherited from FuelCellShop::Material::BaseMaterial
BaseMaterial ()
Constructor.
BaseMaterial (const std::string &name)
Constructor.
virtual ~BaseMaterial ()
Destructor.
Static Protected Member Functions
Instance Delivery (Private and static)
static _mapFactory * get_mapFactory ()
Protected Attributes
Internal variables
double electrical_conductivity
Electrical conductivity [S/cm] of catalyst support extrapolated to 100% solid phase.
double thermal_conductivity
Thermal conductivity [W/(cm-K)] of catalyst support extrapolated to 100% solid phase.
double density
Density of catalyst support [gm/cm^3].
Protected Attributes inherited from FuelCellShop::Material::BaseMaterial
const std::string name
Name of the layer.
std::vector< VariableNames > derivative_flags
Flags for derivatives: These flags are used to request derivatives.
Detailed Description
This class implements the interface to compute the properties of a "standard" catalyst support.
Note that there are many types of catalyst supports such as carbon black, carbon nanotubes and 3M organic nano-wiskers. This class serves a common interface for each one of these types. Children should be implemented for each type with appropriate propertes. The properties of each catalyst support materials are implemented in the children classes. This class is used to return physical properties such as density, electrical conductivity and thermal conductivity. This class is normally not required to be used inside the application. Instead, it's used inside the catalyst layer classes to access these above-mentioned physical properties.
Usage Details:
Three accessors methods are available, viz., get_density, get_electrical_conductivity, get_thermal_conductivity, which return double values corresponding to density [gm/cm^3], electrical conductivity [S/cm] and thermal conductivity [W/(cm-K)] respectively, of the catalyst support material.
Author
M. Secanell, 2011-13
Madhur Bhaiya, 2013
Member Typedef Documentation
typedef std::map< std::string, FuelCellShop::Material::CatalystSupportBase* > FuelCellShop::Material::CatalystSupportBase::_mapFactory protected
This object is used to store all objects of type CatalystSupportBase.
Constructor & Destructor Documentation
FuelCellShop::Material::CatalystSupportBase::CatalystSupportBase () inline protected
Constructor.
FuelCellShop::Material::CatalystSupportBase::CatalystSupportBase (std::string name) inline protected
Constructor The constructor initialize parameters using the default values.
This is so that if I do not want to call declare_parameters and initialize, I can still use the routine with the hard coded values.
High Priority Todo:
What are we going to do with the Carbon, Nafion, Platinum, etc. classes? i.e. puresolids
FuelCellShop::Material::CatalystSupportBase::~CatalystSupportBase () inline protected
Destructor.
Member Function Documentation
static boost::shared_ptr<FuelCellShop::Material::CatalystSupportBase > FuelCellShop::Material::CatalystSupportBase::create_CatalystSupport (ParameterHandler & param, std::string support_name) inline static
Function called in create_CatalystLayer and used to select the appropriate CatalystSupportBase children that will be used in the layer.
The name of the CatalystSupportBase children object to be used is provided in support_name.
The name of the CatalystSupportBase children object is provided in the ParameterHandler in the CatalystLayer subsection as follows:
subsection Catalyst Layer Properties <- This name is the name of the catalyst layer subsection where the kinetics are taking place.
(...)
  set Catalyst support type = CarbonBlack
(...)
end
current options are [ CarbonBlack ]
References get_mapFactory().
virtual boost::shared_ptr<FuelCellShop::Material::CatalystSupportBase > FuelCellShop::Material::CatalystSupportBase::create_replica () inline protected virtual
This member function is used to create an object of type CatalystSupportBase.
Warning
This class MUST be redeclared in every child.
Reimplemented in FuelCellShop::Material::CarbonBlack.
static void FuelCellShop::Material::CatalystSupportBase::declare_CatalystSupport_parameters (ParameterHandler & param) inline static
Function used to declare all the data necessary in the parameter files for all CatalystSupportBase children.
References get_mapFactory().
virtual void FuelCellShop::Material::CatalystSupportBase::declare_parameters (ParameterHandler & param) const inline protected virtual
Declare parameters for a parameter file.
Warning
This is a PureFunction and it does not declare anything, so please do not call this function in the children.
Deprecated:
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonBlack.
virtual double FuelCellShop::Material::CatalystSupportBase::get_density () const inline virtual
Obtain the density [gm/cm^3].
Note
This is an abstract virtual function. Please look at the child classes for its reimplementations (if any).
Reimplemented in FuelCellShop::Material::CarbonBlack.
virtual double FuelCellShop::Material::CatalystSupportBase::get_electrical_conductivity () const inline virtual
Obtain the electrical conductivity [S/cm].
Note
This is an abstract virtual function. Please look at the child classes for its reimplementations (if any).
Reimplemented in FuelCellShop::Material::CarbonBlack.
static _mapFactory* FuelCellShop::Material::CatalystSupportBase::get_mapFactory () inline static protected
Referenced by create_CatalystSupport(), declare_CatalystSupport_parameters(), and set_CatalystSupport_parameters().
virtual double FuelCellShop::Material::CatalystSupportBase::get_thermal_conductivity () const inline virtual
Obtain the thermal conductivity [W/(cm-K)].
Note
This is an abstract virtual function. Please look at the child classes for its reimplementations (if any).
Reimplemented in FuelCellShop::Material::CarbonBlack.
virtual void FuelCellShop::Material::CatalystSupportBase::initialize (ParameterHandler & param) inline protected virtual
Initialize parameters.
Warning
This is a PureFunction and it does not declare anything, so please do not call this function in the children.
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonBlack.
static void FuelCellShop::Material::CatalystSupportBase::set_CatalystSupport_parameters (const std::vector< std::string > & name_dvar, const std::vector< double > & value_dvar, ParameterHandler & param) inline static
References get_mapFactory().
virtual void FuelCellShop::Material::CatalystSupportBase::set_parameters (const std::vector< std::string > & name_dvar, const std::vector< double > & value_dvar, ParameterHandler & param) inline protected virtual
Member function used to change the values in the parameter file for a given list of parameters.
name_dvar should ideally contain the string as it would appear in the input file, i.e. "Thickness of the agglomerate radius"
value_dvar contains the value that the variable should be set at
param is the ParameterHandler that contains all the information that has been read from file
Warning
This is a PureFunction and it does not declare anything, so please do not call this function in the children.
Deprecated:
Reimplemented from FuelCellShop::Material::BaseMaterial.
Reimplemented in FuelCellShop::Material::CarbonBlack.
Member Data Documentation
double FuelCellShop::Material::CatalystSupportBase::density protected
Density of catalyst support [gm/cm^3].
Referenced by FuelCellShop::Material::CarbonBlack::get_density().
double FuelCellShop::Material::CatalystSupportBase::electrical_conductivity protected
Electrical conductivity [S/cm] of catalyst support extrapolated to 100% solid phase.
Referenced by FuelCellShop::Material::CarbonBlack::get_electrical_conductivity().
double FuelCellShop::Material::CatalystSupportBase::thermal_conductivity protected
Thermal conductivity [W/(cm-K)] of catalyst support extrapolated to 100% solid phase.
Referenced by FuelCellShop::Material::CarbonBlack::get_thermal_conductivity().
The documentation for this class was generated from the following file:
catalyst_support_base.h